# Vertical Pod Autoscaler for Banking Services
# Automatically adjusts CPU and memory requests/limits based on usage

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: banking-app-vpa
  namespace: banking-system
  labels:
    app: banking-app
    component: vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: banking-app-deployment
  updatePolicy:
    updateMode: "Auto"  # Automatically apply recommendations
  resourcePolicy:
    containerPolicies:
    - containerName: banking-app
      minAllowed:
        cpu: 500m
        memory: 1Gi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
# VPA for Loan Service with Banking-Specific Resource Patterns
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: loan-service-vpa
  namespace: banking-system
  labels:
    app: loan-service
    component: vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loan-service-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: loan-service
      minAllowed:
        cpu: 250m
        memory: 512Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
# VPA for Payment Service with Conservative Updates
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: payment-service-vpa
  namespace: banking-system
  labels:
    app: payment-service
    component: vpa
    criticality: high
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service-deployment
  updatePolicy:
    updateMode: "Off"  # Manual approval for critical payment service
  resourcePolicy:
    containerPolicies:
    - containerName: payment-service
      minAllowed:
        cpu: 500m
        memory: 1Gi
      maxAllowed:
        cpu: 3000m
        memory: 6Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
# VPA for AI Service with ML-Optimized Settings
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ai-service-vpa
  namespace: banking-system
  labels:
    app: ai-service
    component: vpa
    workload-type: ml
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-service-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: ai-service
      minAllowed:
        cpu: 1000m
        memory: 2Gi
      maxAllowed:
        cpu: 8000m
        memory: 16Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
# VPA for Customer Service
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: customer-service-vpa
  namespace: banking-system
  labels:
    app: customer-service
    component: vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-service-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: customer-service
      minAllowed:
        cpu: 200m
        memory: 256Mi
      maxAllowed:
        cpu: 1500m
        memory: 3Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits