# Enterprise Banking System - Functional Testing Environment
# Simplified setup for comprehensive regression testing

services:
  # === DATABASE ===
  postgres-test:
    image: postgres:15-alpine
    container_name: banking-postgres-test
    environment:
      POSTGRES_DB: banking_test
      POSTGRES_USER: banking_test
      POSTGRES_PASSWORD: banking_test_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking_test -d banking_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - banking-test-network

  # === CACHE ===
  redis-test:
    image: redis:7-alpine
    container_name: banking-redis-test
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - banking-test-network

  # === BANKING APPLICATION ===
  banking-app-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: enterprise-loan-system:test
    container_name: banking-loan-management-test
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    environment:
      # Spring Configuration
      SPRING_PROFILES_ACTIVE: test,docker
      SERVER_PORT: 8080
      
      # Database Configuration
      DATABASE_URL: jdbc:postgresql://postgres-test:5432/banking_test
      DATABASE_USERNAME: banking_test
      DATABASE_PASSWORD: banking_test_pass
      
      # Cache Configuration
      REDIS_HOST: redis-test
      REDIS_PORT: 6379
      
      # Disable complex features for testing
      SPRING_CLOUD_CONFIG_ENABLED: false
      
      # Banking Configuration
      LOAN_MAX_AMOUNT: 5000000
      TRANSACTION_DAILY_LIMIT: 50000
      
      # Application Metadata
      APP_NAME: "Enterprise Loan Management System - Test"
      APP_VERSION: "1.0.0-test"
      
      # JVM Configuration
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=75.0
        -Djava.security.egd=file:/dev/./urandom
        -Dspring.profiles.active=test,docker
        -Dfile.encoding=UTF-8
        -Duser.timezone=UTC
    ports:
      - "8081:8080"
    volumes:
      - banking_test_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - banking-test-network

# === VOLUMES ===
volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local
  banking_test_logs:
    driver: local

# === NETWORKS ===
networks:
  banking-test-network:
    driver: bridge
    name: banking-test-network