package com.amanahfi.compliance.domain.check;

/**
 * Types of compliance violations
 */
public enum ViolationType {
    SANCTIONS_LIST_MATCH,
    SUSPICIOUS_TRANSACTION_PATTERN,
    INCOMPLETE_DOCUMENTATION,
    EXCEEDS_TRANSACTION_LIMITS,
    POLITICALLY_EXPOSED_PERSON,
    HIGH_RISK_JURISDICTION,
    UNUSUAL_ACCOUNT_ACTIVITY,
    IDENTITY_VERIFICATION_FAILURE,
    SHARIA_NON_COMPLIANCE,
    REGULATORY_BREACH
}