# Enterprise Banking Kafka Topics Configuration
# Production-ready topic configuration for banking industry standards

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-customer-onboarding-kyc-completed-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: customer
    banking.subdomain: onboarding
    data.classification: pii
    compliance.level: high
spec:
  partitions: 30
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 31536000000  # 1 year
    segment.ms: 86400000       # 1 day
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-transaction-payments-processed-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: transaction
    banking.subdomain: payments
    data.classification: financial
    volume: high
spec:
  partitions: 200
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: lz4
    retention.ms: 2592000000   # 30 days
    segment.ms: 3600000        # 1 hour
    min.insync.replicas: 2
    max.message.bytes: 10485760  # 10MB

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-account-events-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: account
    pattern: event-sourcing
    retention: long-term
spec:
  partitions: 100
  replicas: 3
  config:
    cleanup.policy: compact
    compression.type: snappy
    retention.ms: 315360000000  # 10 years
    segment.ms: 604800000       # 7 days
    min.insync.replicas: 2
    min.cleanable.dirty.ratio: 0.1
    delete.retention.ms: 86400000

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-compliance-aml-monitoring-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: compliance
    banking.subdomain: aml
    data.classification: confidential
    regulatory: required
spec:
  partitions: 50
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 157680000000  # 5 years
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 3      # Higher for compliance

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-fraud-transaction-flagged-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: fraud
    banking.subdomain: detection
    priority: critical
spec:
  partitions: 75
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: lz4
    retention.ms: 94608000000   # 3 years
    segment.ms: 3600000         # 1 hour
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-credit-assessment-completed-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: credit
    banking.subdomain: assessment
    data.classification: sensitive
spec:
  partitions: 40
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 220752000000  # 7 years
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-ai-model-inference-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: ai
    banking.subdomain: inference
    workload.type: ml
spec:
  partitions: 60
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: lz4
    retention.ms: 7776000000    # 90 days
    segment.ms: 3600000         # 1 hour
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-saga-loan-origination-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: saga
    banking.subdomain: loan-origination
    pattern: choreography
spec:
  partitions: 25
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 31536000000   # 1 year
    segment.ms: 21600000        # 6 hours
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-treasury-liquidity-calculated-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: treasury
    banking.subdomain: liquidity
    regulatory: basel3
spec:
  partitions: 20
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 220752000000  # 7 years
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-digital-session-events-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: digital
    banking.subdomain: session
    channel: mobile
spec:
  partitions: 80
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: lz4
    retention.ms: 7776000000    # 90 days
    segment.ms: 3600000         # 1 hour
    min.insync.replicas: 2

---
# Berlin Group PSD2 Compliance Topic
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-psd2-berlin-group-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: compliance
    banking.subdomain: psd2
    standard: berlin-group
    region: eu
spec:
  partitions: 35
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 220752000000  # 7 years
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 3

---
# BIAN Service Domain Events
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-bian-service-domain-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: bian
    banking.subdomain: service-domain
    standard: bian
spec:
  partitions: 30
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 157680000000  # 5 years
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 2

---
# Islamic Banking Specific Topics
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-islamic-shariah-compliance-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: islamic
    banking.subdomain: shariah
    compliance.type: islamic
spec:
  partitions: 25
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 220752000000  # 7 years
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 2

---
# Multi-Language Support Events
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-localization-events-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: localization
    banking.subdomain: i18n
    languages: ar,en,fr,de
spec:
  partitions: 20
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 31536000000   # 1 year
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 2

---
# Dead Letter Queue for Failed Events
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-dlq-failed-events-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: infrastructure
    banking.subdomain: dlq
    purpose: error-handling
spec:
  partitions: 10
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 31536000000   # 1 year
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 2

---
# Circuit Breaker Events
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-circuit-breaker-events-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: infrastructure
    banking.subdomain: resilience
    pattern: circuit-breaker
spec:
  partitions: 15
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: lz4
    retention.ms: 604800000     # 7 days
    segment.ms: 3600000         # 1 hour
    min.insync.replicas: 2

---
# Rate Limiting Events
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-rate-limit-events-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: infrastructure
    banking.subdomain: rate-limiting
    pattern: throttling
spec:
  partitions: 12
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: lz4
    retention.ms: 2592000000    # 30 days
    segment.ms: 3600000         # 1 hour
    min.insync.replicas: 2

---
# External System Integration Events
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-external-credit-bureau-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: external
    banking.subdomain: credit-bureau
    integration.type: api
spec:
  partitions: 30
  replicas: 3
  config:
    cleanup.policy: delete
    compression.type: snappy
    retention.ms: 94608000000   # 3 years
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 2

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: banking-external-regulatory-updates-v1
  namespace: banking-kafka
  labels:
    strimzi.io/cluster: banking-kafka-cluster
    banking.domain: external
    banking.subdomain: regulatory
    source: government
spec:
  partitions: 10
  replicas: 3
  config:
    cleanup.policy: compact
    compression.type: snappy
    retention.ms: 315360000000  # 10 years
    segment.ms: 86400000        # 1 day
    min.insync.replicas: 3