apiVersion: v2
name: enterprise-loan-system
description: Istio Service Mesh Enterprise Banking System with Microservices Architecture
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - banking
  - loan-management
  - istio
  - service-mesh
  - microservices
  - distributed-redis
  - fintech
  - java
  - spring-boot
home: https://github.com/your-org/enterprise-loan-system
sources:
  - https://github.com/your-org/enterprise-loan-system
maintainers:
  - name: Copur
    email: copur@alico.com
  - name: AliCo Banking Platform Team
    email: platform@alico.com
dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.15.6"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "23.4.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.60.4"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
annotations:
  category: Banking
  licenses: MIT