apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: banking-root-ca
  namespace: istio-system
  labels:
    app: banking-security
    type: root-ca
    compliance: fapi-2.0
spec:
  secretName: banking-root-ca-secret
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  subject:
    countries:
      - US
    provinces:
      - California
    localities:
      - San Francisco
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - Banking Security
  commonName: Enterprise Banking Root CA
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: banking-ca-issuer
  namespace: banking
  labels:
    app: banking-security
    type: ca-issuer
spec:
  ca:
    secretName: banking-intermediate-ca-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: banking-intermediate-ca
  namespace: banking
  labels:
    app: banking-security
    type: intermediate-ca
    compliance: fapi-2.0
spec:
  secretName: banking-intermediate-ca-secret
  duration: 43800h # 5 years
  renewBefore: 720h # 30 days
  subject:
    countries:
      - US
    provinces:
      - California
    localities:
      - San Francisco
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - Banking Services CA
  commonName: Enterprise Banking Intermediate CA
  isCA: true
  issuerRef:
    name: banking-root-ca-issuer
    kind: ClusterIssuer

---
# Service certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loan-service-cert
  namespace: banking
  labels:
    app: loan-service
    compliance: fapi-2.0
spec:
  secretName: loan-service-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - Loan Services
  commonName: loan-service.banking.svc.cluster.local
  dnsNames:
  - loan-service
  - loan-service.banking
  - loan-service.banking.svc
  - loan-service.banking.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    name: banking-ca-issuer
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: payment-service-cert
  namespace: banking
  labels:
    app: payment-service
    compliance: pci-dss
spec:
  secretName: payment-service-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - Payment Services
  commonName: payment-service.banking.svc.cluster.local
  dnsNames:
  - payment-service
  - payment-service.banking
  - payment-service.banking.svc
  - payment-service.banking.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    name: banking-ca-issuer
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: customer-service-cert
  namespace: banking
  labels:
    app: customer-service
    compliance: gdpr
spec:
  secretName: customer-service-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - Customer Services
  commonName: customer-service.banking.svc.cluster.local
  dnsNames:
  - customer-service
  - customer-service.banking
  - customer-service.banking.svc
  - customer-service.banking.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    name: banking-ca-issuer
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-service-cert
  namespace: banking
  labels:
    app: ai-service
    compliance: fapi-2.0
spec:
  secretName: ai-service-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - AI Services
  commonName: ai-service.banking.svc.cluster.local
  dnsNames:
  - ai-service
  - ai-service.banking
  - ai-service.banking.svc
  - ai-service.banking.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    name: banking-ca-issuer
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audit-service-cert
  namespace: banking
  labels:
    app: audit-service
    compliance: sox
spec:
  secretName: audit-service-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - Audit Services
  commonName: audit-service.banking.svc.cluster.local
  dnsNames:
  - audit-service
  - audit-service.banking
  - audit-service.banking.svc
  - audit-service.banking.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    name: banking-ca-issuer
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: compliance-service-cert
  namespace: banking
  labels:
    app: compliance-service
    compliance: multiple
spec:
  secretName: compliance-service-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - Compliance Services
  commonName: compliance-service.banking.svc.cluster.local
  dnsNames:
  - compliance-service
  - compliance-service.banking
  - compliance-service.banking.svc
  - compliance-service.banking.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    name: banking-ca-issuer
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth

---
# External API certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-api-client-cert
  namespace: banking
  labels:
    app: external-api
    type: client-cert
    compliance: fapi-2.0
spec:
  secretName: external-api-client-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - External API Client
  commonName: banking-api-client.enterprisebank.com
  emailAddresses:
  - api-team@enterprisebank.com
  issuerRef:
    name: banking-ca-issuer
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
  - client auth

---
# Gateway certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: banking-gateway-cert
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    compliance: fapi-2.0
spec:
  secretName: banking-gateway-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - API Gateway
  commonName: api.enterprisebank.com
  dnsNames:
  - api.enterprisebank.com
  - openbanking.enterprisebank.com
  - secure.enterprisebank.com
  - "*.api.enterprisebank.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  usages:
  - digital signature
  - key encipherment
  - server auth

---
# Webhook certificates for sidecar injection
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: banking-webhook-cert
  namespace: banking
  labels:
    app: banking-webhook
    type: webhook-cert
spec:
  secretName: banking-webhook-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Enterprise Bank
    organizationalUnits:
      - Banking Infrastructure
  commonName: banking-sidecar-injector.banking.svc
  dnsNames:
  - banking-sidecar-injector
  - banking-sidecar-injector.banking
  - banking-sidecar-injector.banking.svc
  - banking-sidecar-injector.banking.svc.cluster.local
  issuerRef:
    name: banking-ca-issuer
    kind: Issuer
  usages:
  - digital signature
  - key encipherment
  - server auth

---
# ClusterIssuer for Let's Encrypt production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: banking-security
    type: public-ca
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: security@enterprisebank.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: istio
    - dns01:
        cloudDNS:
          project: enterprise-banking-prod
          serviceAccountSecretRef:
            name: clouddns-dns01-solver
            key: key.json

---
# ClusterIssuer for Let's Encrypt staging (testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app: banking-security
    type: public-ca-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: security@enterprisebank.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
        ingress:
          class: istio

---
# Self-signed issuer for development
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  labels:
    app: banking-security
    type: self-signed
spec:
  selfSigned: {}

---
# Root CA issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: banking-root-ca-issuer
  labels:
    app: banking-security
    type: root-ca-issuer
spec:
  ca:
    secretName: banking-root-ca-secret