apiVersion: v1
kind: ServiceAccount
metadata:
  name: loan-service
  namespace: banking
  labels:
    app: loan-service
    compliance: fapi-2.0
    security-level: high
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: banking
  labels:
    app: payment-service
    compliance: pci-dss
    security-level: critical
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service
  namespace: banking
  labels:
    app: customer-service
    compliance: gdpr
    security-level: high
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-service
  namespace: banking
  labels:
    app: ai-service
    compliance: fapi-2.0
    security-level: high
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
  namespace: banking
  labels:
    app: audit-service
    compliance: sox
    security-level: critical
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-service
  namespace: banking
  labels:
    app: compliance-service
    compliance: multiple
    security-level: critical
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service
  namespace: banking
  labels:
    app: account-service
    compliance: fapi-2.0
    security-level: high
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-initiation-service
  namespace: banking
  labels:
    app: payment-initiation-service
    compliance: psd2
    security-level: critical
automountServiceAccountToken: true

---
# RBAC for service accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: banking-service-reader
  namespace: banking
  labels:
    app: banking-security
    type: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loan-service-reader
  namespace: banking
  labels:
    app: loan-service
    type: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: banking-service-reader
subjects:
- kind: ServiceAccount
  name: loan-service
  namespace: banking

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payment-service-reader
  namespace: banking
  labels:
    app: payment-service
    type: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: banking-service-reader
subjects:
- kind: ServiceAccount
  name: payment-service
  namespace: banking

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: customer-service-reader
  namespace: banking
  labels:
    app: customer-service
    type: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: banking-service-reader
subjects:
- kind: ServiceAccount
  name: customer-service
  namespace: banking

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-service-reader
  namespace: banking
  labels:
    app: ai-service
    type: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: banking-service-reader
subjects:
- kind: ServiceAccount
  name: ai-service
  namespace: banking

---
# Audit service needs additional permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: audit-service-writer
  namespace: banking
  labels:
    app: audit-service
    type: rbac
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: audit-service-writer
  namespace: banking
  labels:
    app: audit-service
    type: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audit-service-writer
subjects:
- kind: ServiceAccount
  name: audit-service
  namespace: banking

---
# Compliance service needs cross-namespace access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compliance-service-reader
  labels:
    app: compliance-service
    type: rbac
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["security.istio.io"]
  resources: ["authorizationpolicies", "peerauthentications"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compliance-service-reader
  labels:
    app: compliance-service
    type: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: compliance-service-reader
subjects:
- kind: ServiceAccount
  name: compliance-service
  namespace: banking

---
# Service account for external API access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-api-client
  namespace: banking
  labels:
    app: external-api
    compliance: fapi-2.0
    security-level: high
  annotations:
    description: "Service account for accessing external banking APIs"
automountServiceAccountToken: true

---
# Secret for external API credentials
apiVersion: v1
kind: Secret
metadata:
  name: external-api-credentials
  namespace: banking
  labels:
    app: external-api
    compliance: fapi-2.0
type: Opaque
stringData:
  client-id: "banking-api-client"
  client-secret: "change-me-in-production"
  api-key: "change-me-in-production"

---
# ConfigMap for service account annotations
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-account-config
  namespace: banking
  labels:
    app: banking-security
    type: configuration
data:
  service-accounts.yaml: |
    service_accounts:
      loan-service:
        compliance_frameworks:
          - FAPI-2.0
          - Basel-III
        data_classification: sensitive
        allowed_operations:
          - loan_origination
          - credit_check
          - risk_assessment
      payment-service:
        compliance_frameworks:
          - PCI-DSS
          - FAPI-2.0
          - PSD2
        data_classification: highly_sensitive
        allowed_operations:
          - payment_processing
          - fund_transfer
          - payment_authorization
      customer-service:
        compliance_frameworks:
          - GDPR
          - CCPA
          - FAPI-2.0
        data_classification: pii
        allowed_operations:
          - customer_management
          - kyc_verification
          - consent_management
      ai-service:
        compliance_frameworks:
          - FAPI-2.0
          - AI-Ethics
        data_classification: sensitive
        allowed_operations:
          - loan_recommendation
          - risk_analysis
          - fraud_detection
      audit-service:
        compliance_frameworks:
          - SOX
          - ISO-27001
        data_classification: regulatory
        allowed_operations:
          - audit_logging
          - compliance_reporting
          - event_tracking
      compliance-service:
        compliance_frameworks:
          - ALL
        data_classification: regulatory
        allowed_operations:
          - compliance_validation
          - regulatory_reporting
          - policy_enforcement