# Development Environment Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:}

# Database Configuration
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/banking_dev}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
      minimum-idle: ${DB_POOL_MIN_IDLE:2}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      leak-detection-threshold: ${DB_LEAK_DETECTION:60000}

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:5000}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:10}
          max-idle: ${REDIS_POOL_MAX_IDLE:5}
          min-idle: ${REDIS_POOL_MIN_IDLE:1}

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:loan-management-dev}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Banking Business Configuration
banking:
  threads:
    virtual:
      enabled: true
      scheduled-pool-size: 10
      fallback-core-pool-size: 10
      fallback-max-pool-size: 50
      fallback-queue-capacity: 100
      fallback-keep-alive-seconds: 60
      shutdown-timeout-seconds: 30
  business:
    loan:
      interest-rate:
        min: ${LOAN_MIN_INTEREST_RATE:0.1}
        max: ${LOAN_MAX_INTEREST_RATE:0.5}
      installments:
        allowed: ${LOAN_ALLOWED_INSTALLMENTS:6,9,12,24}
      amount:
        min: ${LOAN_MIN_AMOUNT:1000.00}
        max: ${LOAN_MAX_AMOUNT:500000.00}
    
    payment:
      advance-limit-months: ${PAYMENT_ADVANCE_LIMIT:3}
      discount-rate: ${PAYMENT_DISCOUNT_RATE:0.001}
      penalty-rate: ${PAYMENT_PENALTY_RATE:0.001}
    
    credit-scoring:
      min-score: ${CREDIT_MIN_SCORE:300}
      max-score: ${CREDIT_MAX_SCORE:850}
      high-risk-threshold: ${CREDIT_HIGH_RISK_THRESHOLD:650}
      excellent-threshold: ${CREDIT_EXCELLENT_THRESHOLD:750}

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:banking-dev-secret-key-change-in-production}
    expiration-hours: ${JWT_EXPIRATION_HOURS:1}
    refresh-expiration-hours: ${JWT_REFRESH_EXPIRATION_HOURS:24}
    issuer: ${JWT_ISSUER:https://dev-auth.bank.com}
    audience: ${JWT_AUDIENCE:loan-management-system}
    algorithm: ${JWT_ALGORITHM:HS512}
  
  bcrypt:
    strength: ${BCRYPT_STRENGTH:10}
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    max-age: ${CORS_MAX_AGE:3600}
  
  rate-limiting:
    requests-per-minute: ${RATE_LIMIT_RPM:100}
    burst-limit: ${RATE_LIMIT_BURST:20}
    window-size-ms: ${RATE_LIMIT_WINDOW:60000}

# Cache Configuration
cache:
  ttl:
    customers-minutes: ${CACHE_TTL_CUSTOMERS:30}
    loans-minutes: ${CACHE_TTL_LOANS:15}
    payments-minutes: ${CACHE_TTL_PAYMENTS:5}
    credit-assessment-minutes: ${CACHE_TTL_CREDIT:60}
    compliance-minutes: ${CACHE_TTL_COMPLIANCE:360}
    security-minutes: ${CACHE_TTL_SECURITY:2}
    rate-limit-minutes: ${CACHE_TTL_RATE_LIMIT:1}

# Integration Configuration
integrations:
  openai:
    api-key: ${OPENAI_API_KEY:}
    timeout-seconds: ${OPENAI_TIMEOUT:30}
    model: ${OPENAI_MODEL:gpt-4}
  
  microservices:
    customer-service:
      url: ${CUSTOMER_SERVICE_URL:http://localhost:8081}
      timeout: ${CUSTOMER_SERVICE_TIMEOUT:5000}
    loan-service:
      url: ${LOAN_SERVICE_URL:http://localhost:8082}
      timeout: ${LOAN_SERVICE_TIMEOUT:5000}
    payment-service:
      url: ${PAYMENT_SERVICE_URL:http://localhost:8083}
      timeout: ${PAYMENT_SERVICE_TIMEOUT:5000}
    discovery-service:
      url: ${DISCOVERY_SERVICE_URL:http://localhost:8761}

# GraphQL Configuration
graphql:
  playground:
    endpoint: ${GRAPHQL_ENDPOINT:/graphql}
    subscription-endpoint: ${GRAPHQL_SUBSCRIPTION_ENDPOINT:/graphql}
  settings:
    editor-theme: ${GRAPHQL_THEME:dark}
    editor-font-size: ${GRAPHQL_FONT_SIZE:14}
    timeout-seconds: ${GRAPHQL_TIMEOUT:30}

# Monitoring and Management
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,metrics,prometheus}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_DETAILS:always}
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}

# Logging Configuration
logging:
  level:
    com.bank.loanmanagement: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    org.springframework.kafka: ${LOG_LEVEL_KAFKA:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:DEBUG}
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}
    file: ${LOG_PATTERN_FILE:%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n}