server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: enterprise-loan-management-minimal
  
  # Use H2 in-memory database for minimal testing
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
  
  # Disable external dependencies for minimal testing
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.cloud.autoconfigure.RefreshAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.graphql.GraphQlAutoConfiguration
      - org.springframework.boot.autoconfigure.graphql.servlet.GraphQlWebMvcAutoConfiguration
      - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.netflix.eureka.config.EurekaClientConfigServerAutoConfiguration
      - org.springframework.cloud.netflix.eureka.reactive.EurekaReactiveDiscoveryClientConfiguration
      - org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClientAutoConfiguration
      - org.springframework.cloud.discovery.client.simple.SimpleDiscoveryClientAutoConfiguration
      - org.springframework.cloud.stream.binder.kafka.config.KafkaStreamsBinderSupportAutoConfiguration
      - org.springframework.cloud.stream.config.BindingServiceConfiguration
      - org.springframework.cloud.loadbalancer.config.LoadBalancerAutoConfiguration
      - org.springframework.cloud.openfeign.FeignAutoConfiguration
  
  # Disable Spring Security for testing
  security:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bank.loanmanagement: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.cloud: WARN