global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@enterpriseloan.bank'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'banking-alerts'
  routes:
    - match:
        severity: critical
      receiver: 'critical-banking-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        compliance: banking_standards
      receiver: 'compliance-alerts'
      group_wait: 5s
      repeat_interval: 15m
    - match:
        security: authentication
      receiver: 'security-alerts'
      group_wait: 2s
      repeat_interval: 10m

receivers:
  - name: 'banking-alerts'
    email_configs:
      - to: 'operations@enterpriseloan.bank'
        subject: '[Banking System] Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}
    webhook_configs:
      - url: 'http://localhost:5000/api/v1/monitoring/alerts'
        send_resolved: true

  - name: 'critical-banking-alerts'
    email_configs:
      - to: 'cto@enterpriseloan.bank,compliance@enterprileloan.bank'
        subject: '[CRITICAL] Banking System Alert: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL BANKING SYSTEM ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Time: {{ .StartsAt }}
          
          IMMEDIATE ACTION REQUIRED
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#banking-critical-alerts'
        title: 'Critical Banking System Alert'
        text: '{{ .CommonAnnotations.summary }}'
        color: 'danger'

  - name: 'compliance-alerts'
    email_configs:
      - to: 'compliance@enterpriseloan.bank,audit@enterprileloan.bank'
        subject: '[COMPLIANCE] Banking Standards Alert: {{ .GroupLabels.alertname }}'
        body: |
          BANKING COMPLIANCE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Compliance Type: {{ .Labels.compliance }}
          Time: {{ .StartsAt }}
          
          COMPLIANCE REVIEW REQUIRED
          {{ end }}

  - name: 'security-alerts'
    email_configs:
      - to: 'security@enterpriseloan.bank,ciso@enterprileloan.bank'
        subject: '[SECURITY] Banking System Security Alert: {{ .GroupLabels.alertname }}'
        body: |
          BANKING SECURITY ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Security Domain: {{ .Labels.security }}
          Time: {{ .StartsAt }}
          
          SECURITY INCIDENT RESPONSE REQUIRED
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']