# Data Residency Configuration for Asia-Pacific Region
# Multi-jurisdictional Compliance (Australia, Singapore, Japan, etc.)

data_residency:
  region: "APAC"
  primary_jurisdiction: "Australia"
  secondary_jurisdictions:
    - "Singapore"
    - "Japan" 
    - "Hong Kong"
    - "New Zealand"
  regulatory_framework: "MULTI_JURISDICTIONAL"
  
# Australia Privacy Act Configuration
privacy_act_australia:
  enabled: true
  notifiable_data_breaches: true
  privacy_principles: 13
  credit_reporting: true
  
# Singapore PDPA Configuration  
pdpa_singapore:
  enabled: true
  consent_obligation: true
  notification_obligation: true
  access_obligation: true
  correction_obligation: true
  
# Japan APPI Configuration
appi_japan:
  enabled: true
  personal_information_protection: true
  cross_border_transfer_consent: true
  
# PCI-DSS v4 Configuration (APAC)
pci_dss:
  version: "4.0"
  enabled: true
  merchant_level: 1
  apac_specific_requirements:
    - "A1.1.1" # Regional compliance mapping
    - "A6.5.1" # Multi-jurisdictional controls

# Data Storage Configuration
storage:
  elasticsearch:
    region: "ap-southeast-2"
    endpoint: "https://search-banking-logs-apac.ap-southeast-2.es.amazonaws.com"
    encryption_at_rest: true
    encryption_in_transit: true
    index_pattern: "banking-logs-apac-%{+yyyy.MM.dd}"
    multi_jurisdiction_compliant: true
    
  s3:
    region: "ap-southeast-2"
    bucket: "banking-audit-logs-apac"
    storage_class: "STANDARD_IA"
    encryption: "AES256"
    versioning: true
    cross_region_replication:
      singapore: "ap-southeast-1"
      tokyo: "ap-northeast-1"
    
# Compliance Settings by Jurisdiction
compliance:
  australia:
    privacy_act_1988: true
    notifiable_data_breaches_scheme: true
    consumer_data_right: true
    apra_requirements: true
    
  singapore:
    pdpa_2012: true
    monetary_authority_singapore: true
    cybersecurity_act: true
    
  japan:
    appi_2003: true
    cybersecurity_basic_act: true
    financial_instruments_exchange_act: true
    
  hong_kong:
    pdpo_2012: true
    hkma_guidelines: true
    
  new_zealand:
    privacy_act_2020: true
    rbnz_requirements: true
    
# Data Classification Mapping (Multi-jurisdictional)
data_classification:
  personal_information_australia: # Privacy Act 1988
    - "name"
    - "address" 
    - "telephone_number"
    - "email_address"
    - "financial_information"
    
  personal_data_singapore: # PDPA 2012
    - "nric_number"
    - "passport_number"
    - "personal_particulars"
    - "business_contact_information"
    
  personal_information_japan: # APPI 2003
    - "individual_identification"
    - "sensitive_personal_information"
    - "pseudonymous_information"
    
  pci_data_apac:
    - "credit_card_number"
    - "cardholder_name"
    - "bank_card_data"
    - "payment_authentication_data"

# Encryption Configuration (Regional Requirements)
encryption:
  algorithm: "AES-256-GCM"
  key_management: "Regional-HSM"
  key_rotation_days: 90
  jurisdiction_specific:
    australia:
      essential_eight_compliance: true
      information_security_manual: true
    singapore:
      cybersecurity_framework: true
      mtcs_ss584: true
    japan:
      nisc_guidelines: true
      fisc_standards: true

# Log Retention Policies (Multi-jurisdictional)
retention:
  australia:
    audit_logs: "P2555D" # 7 years (APRA requirement)
    personal_information: "P1825D" # 5 years (Privacy Act)
    credit_information: "P1825D" # 5 years (Privacy Act)
    
  singapore:
    audit_logs: "P1825D" # 5 years (MAS requirement)
    personal_data: "P1095D" # 3 years (PDPA)
    financial_records: "P1825D" # 5 years
    
  japan:
    audit_logs: "P1825D" # 5 years (JFSA requirement)
    personal_information: "P1095D" # 3 years (APPI)
    financial_data: "P2555D" # 7 years
    
  default:
    application_logs: "P365D" # 1 year
    security_logs: "P1095D" # 3 years
    performance_logs: "P90D" # 90 days

# Cross-Border Transfer Rules (APAC)
cross_border_transfer:
  australia:
    notifiable_data_breaches: true
    overseas_disclosure: "consent_required"
    
  singapore:
    transfer_limitation_obligation: true
    adequate_protection_standard: true
    
  japan:
    consent_for_overseas_transfer: true
    adequate_protection_measures: true
    
  hong_kong:
    prescribed_consent: true
    data_transfer_impact_assessment: true
    
  allowed_regions:
    - "APAC_REGION_ONLY"
    
  prohibited_data_types:
    - "credit_reporting_information"
    - "sensitive_personal_information"
    - "government_identifiers"

# Data Subject Rights (Multi-jurisdictional)
data_subject_rights:
  australia: # Privacy Act 1988
    access_rights: true
    correction_rights: true
    erasure_rights: "limited"
    response_time: "P30D"
    
  singapore: # PDPA 2012
    access_obligation: true
    correction_obligation: true
    withdrawal_of_consent: true
    response_time: "P30D"
    
  japan: # APPI 2003
    disclosure_rights: true
    correction_rights: true
    suspension_rights: true
    response_time: "P30D"

# Monitoring and Alerting (Multi-jurisdictional)
monitoring:
  data_breach_notification:
    australia:
      notifiable_data_breaches: "PT72H" # 72 hours to OAIC
      affected_individuals: "as_soon_as_practicable"
      
    singapore:
      personal_data_breach: "PT72H" # 72 hours to PDPC
      affected_individuals: "without_undue_delay"
      
    japan:
      personal_information_leakage: "without_delay"
      ppc_notification: "as_soon_as_possible"
      
  compliance_violations:
    enabled: true
    multi_jurisdiction_monitoring: true
    severity_mapping:
      australia: "APRA_SEVERITY_LEVELS"
      singapore: "MAS_SEVERITY_LEVELS" 
      japan: "JFSA_SEVERITY_LEVELS"
      
  cross_border_violations:
    enabled: true
    automatic_blocking: true
    notification_channels:
      - "compliance-apac@bank.com"
      - "legal-apac@bank.com"

# Regional Specific Settings
regional_settings:
  time_zones:
    australia: "Australia/Sydney"
    singapore: "Asia/Singapore"
    japan: "Asia/Tokyo"
    hong_kong: "Asia/Hong_Kong"
    
  business_hours:
    australia: "09:00-17:00 AEDT"
    singapore: "09:00-18:00 SGT"
    japan: "09:00-17:00 JST"
    
  incident_response_teams:
    australia: "irt-australia@bank.com"
    singapore: "irt-singapore@bank.com" 
    japan: "irt-japan@bank.com"
    
  regulatory_contacts:
    australia: "APRA, OAIC, ASIC"
    singapore: "MAS, PDPC"
    japan: "JFSA, PPC"
    hong_kong: "HKMA, PCPD"