# Data Residency Configuration for United States
# PCI-DSS v4 and CCPA Compliance Settings

data_residency:
  region: "US"
  jurisdiction: "United States"
  regulatory_framework: "CCPA"
  
# PCI-DSS v4 Configuration
pci_dss:
  version: "4.0"
  enabled: true
  merchant_level: 1
  requirements:
    - "3.4.1" # Disk encryption
    - "3.5.1" # Key management
    - "10.2.1" # Audit logging
    - "10.3.1" # Log integrity
    - "11.3.1" # Penetration testing
    - "12.10.1" # Incident response

# Data Storage Configuration
storage:
  elasticsearch:
    region: "us-east-1"
    endpoint: "https://search-banking-logs-us.us-east-1.es.amazonaws.com"
    encryption_at_rest: true
    encryption_in_transit: true
    index_pattern: "banking-logs-us-%{+yyyy.MM.dd}"
    
  s3:
    region: "us-east-1"
    bucket: "banking-audit-logs-us"
    storage_class: "STANDARD_IA"
    encryption: "AES256"
    versioning: true
    
# Compliance Settings
compliance:
  ccpa:
    enabled: true
    data_subject_rights: true
    deletion_requests: true
    opt_out_enabled: true
    
  sox:
    enabled: true
    financial_controls: true
    audit_trail_required: true
    
  pci_dss:
    cardholder_data_retention: "P1095D" # 3 years
    authentication_data_retention: "P0D" # Not permitted
    log_retention: "P365D" # 1 year minimum
    
# Data Classification Mapping
data_classification:
  pci_data:
    - "credit_card_number"
    - "cardholder_name" 
    - "expiration_date"
    - "cvv"
    - "magnetic_stripe_data"
    
  sensitive_data:
    - "ssn"
    - "driver_license"
    - "bank_account_number"
    - "routing_number"
    
  pii_data:
    - "email_address"
    - "phone_number"
    - "home_address"
    - "date_of_birth"

# Encryption Configuration
encryption:
  algorithm: "AES-256-GCM"
  key_management: "AWS-KMS"
  key_rotation_days: 90
  field_level_encryption:
    - "account_number"
    - "ssn"
    - "credit_card_number"

# Log Retention Policies
retention:
  audit_logs: "P2555D" # 7 years (SOX requirement)
  transaction_logs: "P1095D" # 3 years (PCI-DSS)
  application_logs: "P365D" # 1 year
  security_logs: "P1095D" # 3 years
  performance_logs: "P90D" # 90 days

# Cross-Border Transfer Rules
cross_border_transfer:
  allowed_regions: []
  prohibited_data_types:
    - "pci_data"
    - "ssn"
    - "financial_data"
  transfer_mechanism: "none"
  
# Monitoring and Alerting
monitoring:
  data_residency_violations:
    enabled: true
    severity: "CRITICAL"
    notification_channels:
      - "compliance-team@bank.com"
      - "security-team@bank.com"
      
  unauthorized_access:
    enabled: true
    threshold: 3
    window: "5m"
    
  audit_log_tampering:
    enabled: true
    checksum_verification: true
    blockchain_anchoring: false