# Istio Installation Configuration for Enterprise Banking
# Optimized for FAPI 2.0 compliance and banking security requirements

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: enterprise-banking-istio
  namespace: istio-system
spec:
  # Use production-ready configuration
  revision: "1-20-stable"
  
  # Global configuration for banking compliance
  values:
    global:
      # Banking mesh configuration
      meshID: "enterprise-banking-mesh"
      network: "banking-network"
      
      # Security configuration for banking
      defaultPodDisruptionBudget:
        enabled: true
        minAvailable: 1
      
      # Banking proxy configuration
      proxy:
        # Enhanced resource limits for banking workloads
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        
        # Banking compliance metadata
        metadata:
          PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true
          BOOTSTRAP_XDS_AGENT: true
          PILOT_ENABLE_CROSS_CLUSTER_WORKLOAD_ENTRY: true
        
        # Tracing for regulatory compliance
        tracer: "jaeger"
        
        # Security hardening
        holdApplicationUntilProxyStarts: true
        
      # Certificate management for banking mTLS
      pilotCertProvider: "istiod"
      
      # Banking mesh expansion
      meshExpansion:
        enabled: true
        
      # External traffic policy for banking APIs
      defaultConfig:
        # mTLS enforcement
        discoveryRefreshDelay: 10s
        configPath: "/etc/istio/proxy"
        binaryPath: "/usr/local/bin/envoy"
        serviceCluster: "istio-proxy"
        drainDuration: 45s
        parentShutdownDuration: 1m0s
        
        # Banking-specific proxy settings
        concurrency: 2
        proxyStatsMatcher:
          inclusionRegexps:
          - ".*circuit_breakers.*"
          - ".*upstream_rq_retry.*"
          - ".*upstream_rq_pending.*"
          - ".*_cx_.*"
          - ".*banking.*"
          - ".*fapi.*"
          - ".*oauth.*"
        
        # FAPI compliance headers
        defaultHeaders:
          request:
            X-Banking-Request-ID: "%REQ(X-REQUEST-ID)%"
            X-Banking-Trace-ID: "%REQ(X-B3-TRACEID)%"
            X-FAPI-Interaction-ID: "%REQ(X-FAPI-INTERACTION-ID)%"
          response:
            X-Banking-Response-Time: "%RESPONSE_DURATION%"
            X-Banking-Instance: "%HOSTNAME%"

  # Components configuration for banking
  components:
    # Pilot configuration for banking mesh
    pilot:
      enabled: true
      k8s:
        # High availability for banking
        replicaCount: 2
        
        # Banking-specific resource allocation
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        
        # Anti-affinity for banking availability
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: istiod
              topologyKey: kubernetes.io/hostname
        
        # Node selection for banking workloads
        nodeSelector:
          banking-workload: "control-plane"
        
        env:
          # Banking-specific pilot configuration
          - name: PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION
            value: "true"
          - name: PILOT_ENABLE_CROSS_CLUSTER_WORKLOAD_ENTRY
            value: "true"
          - name: PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING
            value: "true"
          - name: PILOT_ENABLE_STATUS
            value: "true"
          # Banking compliance settings
          - name: PILOT_FILTER_GATEWAY_CLUSTER_CONFIG
            value: "true"
          - name: PILOT_ENABLE_REDIS_FILTER
            value: "true"
          - name: PILOT_ENABLE_MYSQL_FILTER
            value: "true"

    # Ingress Gateway for banking APIs
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        # Banking API gateway configuration
        replicaCount: 2
        
        # Banking-specific resources
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        
        # Banking service configuration
        service:
          type: LoadBalancer
          loadBalancerIP: ""
          externalTrafficPolicy: Local
          ports:
          # HTTPS for banking APIs (FAPI 2.0)
          - port: 443
            targetPort: 8443
            name: https
            protocol: TCP
          # mTLS for inter-service communication
          - port: 15021
            targetPort: 15021
            name: status-port
            protocol: TCP
          # Banking monitoring
          - port: 15090
            targetPort: 15090
            name: http-envoy-prom
            protocol: TCP
        
        # Banking security labels
        podLabels:
          banking-component: "ingress-gateway"
          compliance-level: "fapi-2.0"
          
        # Banking environment variables
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: "sni-dnat"
        - name: ISTIO_META_HTTP10
          value: "1"
        
        # Node selection for banking gateways
        nodeSelector:
          banking-workload: "gateway"

    # Egress Gateway for external banking integrations
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        # Banking egress configuration
        replicaCount: 2
        
        # Banking-specific resources
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        
        # Banking security labels
        podLabels:
          banking-component: "egress-gateway"
          compliance-level: "fapi-2.0"
        
        # Node selection for banking egress
        nodeSelector:
          banking-workload: "gateway"

  # Additional configuration for banking
  addonComponents:
    # Banking telemetry
    telemetry:
      enabled: true
      
    # Banking tracing
    tracing:
      enabled: true
      
    # Banking metrics
    prometheus:
      enabled: true

---
# Banking-specific ConfigMap for Istio
apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-istio-config
  namespace: istio-system
  labels:
    banking-component: "service-mesh"
    compliance-level: "fapi-2.0"
data:
  # Banking mesh configuration
  mesh: |
    defaultConfig:
      # Banking proxy configuration
      concurrency: 2
      configPath: /etc/istio/proxy
      binaryPath: /usr/local/bin/envoy
      serviceCluster: istio-proxy
      drainDuration: 45s
      parentShutdownDuration: 60s
      interceptionMode: REDIRECT
      proxyStatsMatcher:
        inclusionRegexps:
        - ".*circuit_breakers.*"
        - ".*upstream_rq_retry.*"
        - ".*upstream_rq_pending.*"
        - ".*banking.*"
        - ".*fapi.*"
        - ".*oauth.*"
        - ".*compliance.*"
      
      # Banking tracing configuration
      tracing:
        jaeger:
          address: jaeger-collector.istio-system.svc.cluster.local:14268
        zipkin:
          address: zipkin.istio-system.svc.cluster.local:9411
      
      # Banking discovery configuration
      discoveryRefreshDelay: 10s
      
      # Banking termination drain duration
      terminationDrainDuration: 30s
    
    # Banking mesh-wide settings
    defaultProviders:
      metrics:
      - prometheus
      tracing:
      - jaeger
      accessLogging:
      - envoy
      
    # Banking compliance extensions
    extensionProviders:
    - name: otel
      envoyOtelAls:
        service: opentelemetry-collector.istio-system.svc.cluster.local
        port: 4317
    
    # Banking trust domain
    trustDomain: "banking.enterprise.local"
    
  # Banking network configuration
  networks: |
    networks:
      banking-network:
        endpoints:
        - fromRegistry: kubernetes
        gateways:
        - istio-ingressgateway
        - istio-egressgateway

---
# Banking Service Mesh Registry
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-banking-apis
  namespace: istio-system
  labels:
    banking-component: "external-apis"
    compliance-level: "fapi-2.0"
spec:
  hosts:
  - api.openbanking.org.uk
  - rs.aspsp.ob.forgerock.financial
  - ob19-auth1-ui.o3bank.co.uk
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS

---
# Banking Gateway for External APIs
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: external-banking-gateway
  namespace: istio-system
  labels:
    banking-component: "external-gateway"
    compliance-level: "fapi-2.0"
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - api.openbanking.org.uk
    - rs.aspsp.ob.forgerock.financial
    - ob19-auth1-ui.o3bank.co.uk