# Istio Security Policies for Enterprise Banking
# Comprehensive security configuration for FAPI 2.0 compliance

---
# Banking Root Certificate Authority
apiVersion: v1
kind: Secret
metadata:
  name: banking-root-ca
  namespace: istio-system
  labels:
    banking-component: pki
    compliance-level: fapi-2.0
type: Opaque
data:
  # Base64 encoded root CA certificate
  root-cert.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGakNDQWY2Z0F3SUJBZ0lKQUtQR3dOdEI5
    bkQrTUEwR0NTcUdTSWIzRFFFQkN3VUFNQzR4Q3pBSkJnTlYKQkFZVEFsVlRNUXN3Q1FZRFZRUUlE
    QUpEUVRFUk1BOEdBMVVFQ2d3SVVtVmtTR0YwSUVOQk1CNFhEVEl6TURreApPREE0TkRBME5Gb1hE
    VE16TURrMU1qQTRNemcxTTFvd0xqRUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNCkFrTkJN
    UkV3RHdZRFZRUUtEQWhTWldSSVlYUWdRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3
    QXcKZ2dFS0FvSUJBUURJSVVmcjMwQVJHSTVPeDQ4ZkdOZWdDNjFXdEhHUXNCZUJGZkxKUkZYMWtG
    amlEZWJVWHpnOApGUTg4T2ZYQWJXbDJ0Qzd0Y0R4cU8vQWhVQmxRdWhOUCtjdGNOUmFWS29QMzk0
    bFlnY2l5NXBKL3RxQm1JSmNuCmM4VVB0bG5idlpGZlhsWGttZkRyS3RaU3R1VEd5TjFENGFyS2xJ
    WGU5ZmRqTk10VnZGY0pBRll3eU1ZSXFFcWMKWkNrWDM4QmVrZ2p6WmZZN2hkNE42MkI5WE12SzZl
    K01CMVNzV3VYUENZdEVnVm1GYks3ZUpvTlF3TGpsYmdZMQprMVpiSHFDcmlDenZUZ1E0MEp6SU54
    Q1J1V1Bsa3EvY0lJZCtSclE5RGFVYU1SRitwYXI2OXJHejdCZUVGREtLCkE3VVFqVWN6WGlRb1Ez
    dGVQdk5CWDRXZkFnTUJBQUdqVURCT01CMEdBMVVkRGdRV0JCU3NKOUZNZEVkZG1tZHcKMGFCUXBp
    Q3hNREFmQmdOVkhTTUVHREFXZ0JTc0o5Rk1kRWRkbW1kdzBhQlFwaUN4TURBZkJnTlZIUk1CQWY4
    RUREQUNCZ0F3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhqVnJQNXU4VExaSlQ4cXI3U0hiUEFJ
    VmFLNWloUm9sRkRxCkU0R0p5NkhMcUFiRmdhSjJwbzZFa2gxTDZPQTdZQUs3UEgybHNJMnZmL3hZ
    OEZzNWMybm9JSUcrNkNRRlFnZisKN1J6N3pEUDBSWU1yTHBINTJWNlR1NDlIOWpOUHhNekVhMnh2
    ZjdUZWo1clZmSExESW1LRDA2L1RKcWx1T0ltRgpJRGhNNGZQeTFHbGRsUk5FQkY2K3FneUlwRnU2
    WUpkZlpHT1l5c2VBL0E5dDVEMW8rUjF1NnFrRUFsTzNWWVdrCi9BKzYwLzZiZzMxem9XaXRVajhu
    UFpNZWJIczRrOVlVeUJ3OGhPUi9wNEJCM2hKWXVZZ0hYSGR5RmZaRFY2WVMKMGZkK0xEOWVJUEE2
    clpzOWpOV2duNUEwNHBDL3k4T1hsaGcrOG1IQS8rYUFMc0E9Ci0tLS0tRU5EIENFUlRJRklDQVRF
    LS0tLS0K
  # Base64 encoded root CA private key
  root-key.pem: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeUNGSDY5OUFFUmlP
    VHNlUEh4alhvQXV0VnJSeGtMQVhnUlh5eVVSVjlaQlk0ZzNtCjFGODRQUlVQUERuMXdHMXBkclF1
    N1hBOGFqdndJVkFaVUxvVFQvbkxYRFVXbFNxRDkvZUpXSUhJc3VhU2Y3YWcKWmlDWEozUEZEN1pa
    MjcyUlgxNVY1Sm53NnlyV1VyYmt4c2pkUStHcXlwU0YzdlgzWXpUTFZieFhDUUJXTU1qRwpDS2hL
    bkdRcEY5L0FYcElJODJYMk80WGVEZXRnZlZ6THl1bnZqQWRVckZybHp3bUxSSUZaaFd5dTNpYURV
    TUM0CjVXNEdOWk5XV3g2Z3E0Z3M3MDRFT05DY3lEY1FrYmxqNVpLdjNDQ0hma2EwUFEybEdqRVJm
    cVdxK3ZheHMrd1gKaEJReWlnTzFFSTFITTE0a0tFTjdYajd6UVYrRm53SURBZ01CQUFFZmdnRUFT
    ZjI3T1g4aGJrZTZjRVdDMFdkZgpJSlp1VDNoYTUwK3p2TWR2aDRnQ2piNnZkajNBLzI5blZXSXgz
    bGpMSWg4aGdKTlZ3VG1seHJnSkZTZEV6Vkp2CjYyYURsaTBiYTJ1eEd2V2swZWx3UEdXcUVINFE5
    czJTYVo1SkNUMWFxOFhXWGJYYnljL0VhNytsNUFJeWN2V1oKSzlOd1FFV2NuYWs4MXZRS3djWEpI
    YjVod3RWRzMvdE90THZOK3g1NXNYWGFsWE1kVGRNUGEvRWpoOFJISGN6VwoyZFZGdlBRQUxSSm5a
    YVFsbDdOdStXWVBMblI3aTNRdURYZG1yVnFGdWFtbTkrWC9KNkUreG85VFVPNVJXNXZQCnpqWUdr
    L24ydFZybTZ1U0dyMmJDTThEOWJENGZIaDFadE9USmZuajFyWEh6d001Ny9DdGM1S0FvKzlVRVRk
    cmYKRktIamhUc2xMZEJjQ0l1ZHlaNDBkZzk5VTNYMStlMHk1MWUwMlBMY0ZnQXBDdDN0T3czN2h5
    ZlZHOXBGTHlZNgpMVGJKWjNPRUVRYUVWL1U3L2VLZzlUc0hsOWhiSXJ2d3VlbkNHVEl1dHNFUjF2
    bmUxVjVaOWloV3JwMVBoTEZMCjNWQVFVMXBxYVVKQTZNTGRDTzhIL29WeTZVQ05zWUU5NEEzQ3NZ
    ZjdmeWNLQkFHNHNEUDJwZlhyQ0cvRUdWSVAKVWtGVnQ2UHI3K2pRQXptdXBxSDBSbGFPOUN6ZElk
    TXFMdlBKZng4ZVBzcGM1TTNKaHU5cFowUU4rM1J6N003UAplNWM3U0NBSzVicTY5M3I3U3g4dXM3
    MlR0U0hZdGRYN1k5YzVHR2pvUUVHcThmbXpKWGFVeUV1R0dGUGdOZThGCjNhVTB5VWtDZ1lFQTdG
    amhVR1JRS3JBL0p1cUJvUkNQOSsvckhxdFlRS2trL3N3OWFBSFA3ZE5jcDFnQ2ZCc0IKMDE5azJ0
    SjZWZXJwaTV4V1JtZnE3bGRuSVVCWWMzaHJtRWpjOEptbzJ3NG1YSy9FeTFNdE5CdGFOODZqSzN1
    VgpENmkrRHVNSkxOOGNXbldjRkdxUU02ME5MNW0yMXhDVWExQWh4K1lSSkdBNENUdGN0NWFITUVz
    Q2dZRUEzanduCmJPL0NPODBkWUcreHdJOW5vdER2cURHRVdEVllucW1JYVhaa3R3dGNPQU1CUjFQ
    RWVuRGRoYTBZQnJMT2F5YXMKZkVqNEJOSmpOdGkwK3dpVE0zOWw4QU43YWpFUWZ6aXJPcFFicTBM
    TjJ0TkJuR1lxSCt5VXdsSFlPT245RWxzUQpUM1JvSzArdkp3eDB4d1RxV1RHcS82ZWdXWWJzSlpI
    L3hQdmVmZzBDZ1lFQTIweUdJNE11VHpkQXZod0s4K29PCitGNzE1U3dWTEcwM2RITGRMenZQTzV3
    dVpGQy82b01NdThIbUh6STRVWkxJSFJtS0xxQytUeEFoeFIzNHpDcWkKZU40QXJCZ2RDbW5wTWpF
    N05JZHhyKzFzNGtuTCtCTmJqZGJFeERSMnA5SGNXMStScVdhNFRLVUFXbXhkZCtGbwpZc3A3b3Fi
    VWZCS0J6QXhQeG8vZGU1VUNnWUJOYms4VStCZXpubjVDQlM4cjV6aWhwaThHY3RBNUNjeDdMZHVs
    CmJUc0UrZDlSRW1KZ01KSzVhQ1FEL2JwVHNMUUNUOGdlUGtxaWJkZStBdCtXWFJFN1czS3QzL2Rx
    eG9oenE0M1gKdkNlYWFyTDdRUk1qb0tOS3hpM2tOLzJMUjJYa3NCblc2QzVWdVZ1aWpNZVo3YXBB
    M1dGN1dRNTNsbHUrNGdOMwovMWVhZHdLQmdBcEtGK3JjODFva3Q5TmVKcUdWN3MzdlhKSGl6NWF4
    THFpVUZnLzR5UkZOTERsQTYwN0ozRmhMCjBESkYvb1pVUzRKQ0x2dzA3VUp4UGNMQUNOdXhDVlhj
    R2k3UWl0TjNMUjdHOGVjODgvTEZ0aDhmbnZCaFA4QWgKdjVOZmZQaTJmSFpsSTg5azRpODZJQnpI
    V21hOGF0ajYxeTQ4NzJ1WG1rUXRvSzZ6ODZqTAotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0t
    LQo=

---
# Banking Mesh-wide mTLS Policy
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mesh-wide-mtls
  namespace: istio-system
  labels:
    banking-component: security
    compliance-level: fapi-2.0
spec:
  mtls:
    mode: STRICT

---
# Banking RBAC Authorization Policy
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: banking-rbac-policy
  namespace: banking-services
  labels:
    banking-component: authorization
    compliance-level: fapi-2.0
spec:
  rules:
  # Customer Service Access Rules
  - from:
    - source:
        principals: 
        - "cluster.local/ns/banking-services/sa/customer-service"
        - "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "PATCH"]
    when:
    - key: source.labels[banking-service]
      values: ["customer", "gateway"]

  # Loan Service Access Rules
  - from:
    - source:
        principals:
        - "cluster.local/ns/banking-services/sa/loan-service"
        - "cluster.local/ns/banking-services/sa/customer-service"
        - "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "PATCH"]
        paths: ["/api/v1/loans/*", "/api/v1/eligibility/*"]
    when:
    - key: request.headers[authorization]
      values: ["Bearer *"]
    - key: request.headers[x-fapi-interaction-id]
      values: ["*"]

  # Payment Service Access Rules (Open Banking)
  - from:
    - source:
        principals:
        - "cluster.local/ns/banking-services/sa/payment-service"
        - "cluster.local/ns/banking-services/sa/loan-service"
        - "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
    to:
    - operation:
        methods: ["POST", "GET"]
        paths: ["/open-banking/v3.1/pisp/*", "/api/v1/payments/*"]
    when:
    - key: request.headers[authorization]
      values: ["Bearer *"]
    - key: request.headers[x-fapi-financial-id]
      values: ["*"]
    - key: request.headers[x-fapi-interaction-id]
      values: ["*"]

  # AI Assistant Service Access Rules
  - from:
    - source:
        principals:
        - "cluster.local/ns/banking-services/sa/ai-assistant-service"
        - "cluster.local/ns/banking-services/sa/loan-service"
        - "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
    to:
    - operation:
        methods: ["POST", "GET"]
        paths: ["/api/v1/ai/*", "/api/v1/analysis/*"]
    when:
    - key: request.headers[authorization]
      values: ["Bearer *"]

---
# Banking Network Security Policy
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: banking-network-policy
  namespace: banking-services
  labels:
    banking-component: network-security
    compliance-level: fapi-2.0
spec:
  rules:
  # Allow only encrypted traffic
  - from:
    - source:
        namespaces: ["banking-services", "istio-system"]
    to:
    - operation:
        methods: ["*"]
    when:
    - key: connection.mtls
      values: ["true"]

  # Deny all unencrypted traffic
  - {}
  action: DENY
  when:
  - key: connection.mtls
    notValues: ["true"]

---
# Banking Request Authentication for JWT
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: banking-jwt-policy
  namespace: banking-services
  labels:
    banking-component: jwt-authentication
    compliance-level: fapi-2.0
spec:
  selector:
    matchLabels:
      banking-service-type: api
  jwtRules:
  # Main FAPI 2.0 JWT
  - issuer: "https://auth.banking.enterprise.local"
    jwksUri: "https://auth.banking.enterprise.local/.well-known/jwks.json"
    audiences:
    - "banking-api"
    - "open-banking-api"
    fromHeaders:
    - name: "Authorization"
      prefix: "Bearer "
    forwardOriginalToken: true
    
  # DPoP JWT (RFC 9449)
  - issuer: "https://auth.banking.enterprise.local"
    jwksUri: "https://auth.banking.enterprise.local/.well-known/dpop-jwks.json"
    audiences:
    - "banking-api-dpop"
    fromHeaders:
    - name: "DPoP"
    forwardOriginalToken: true

---
# Banking Authorization Policy for Authenticated Users
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: banking-authenticated-policy
  namespace: banking-services
  labels:
    banking-component: jwt-authorization
    compliance-level: fapi-2.0
spec:
  selector:
    matchLabels:
      banking-service-type: api
  rules:
  # Require valid JWT for all API calls
  - from:
    - source:
        requestPrincipals: ["https://auth.banking.enterprise.local/*"]
    to:
    - operation:
        methods: ["GET", "POST", "PUT", "PATCH", "DELETE"]
    when:
    - key: request.auth.claims[aud]
      values: ["banking-api", "open-banking-api"]
    - key: request.auth.claims[scope]
      values: ["banking:read", "banking:write", "openbanking:read", "openbanking:write"]

  # Allow health checks without authentication
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/health", "/health/*", "/actuator/health"]

---
# Banking Rate Limiting Policy
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: banking-rate-limit
  namespace: banking-services
  labels:
    banking-component: rate-limiting
    compliance-level: fapi-2.0
spec:
  workloadSelector:
    labels:
      banking-service-type: api
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: banking_rate_limiter
            token_bucket:
              max_tokens: 1000
              tokens_per_fill: 100
              fill_interval: 60s
            filter_enabled:
              runtime_key: local_rate_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: local_rate_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED
            response_headers_to_add:
            - append: false
              header:
                key: x-banking-rate-limit-status
                value: '%RESPONSE_CODE%'

---
# Banking Security Headers Policy
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: banking-security-headers
  namespace: banking-services
  labels:
    banking-component: security-headers
    compliance-level: fapi-2.0
spec:
  workloadSelector:
    labels:
      banking-service-type: api
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.headers
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.headers.v3.HeadersConfig
          request_headers_to_add:
          - header:
              key: "X-Banking-Request-Time"
              value: "%START_TIME%"
          - header:
              key: "X-Banking-Request-ID"
              value: "%REQ(X-REQUEST-ID)%"
          response_headers_to_add:
          - header:
              key: "X-Content-Type-Options"
              value: "nosniff"
          - header:
              key: "X-Frame-Options"
              value: "DENY"
          - header:
              key: "X-XSS-Protection"
              value: "1; mode=block"
          - header:
              key: "Strict-Transport-Security"
              value: "max-age=31536000; includeSubDomains"
          - header:
              key: "Content-Security-Policy"
              value: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'"
          - header:
              key: "X-Banking-Service"
              value: "%REQ(X-Banking-Service)%"
          - header:
              key: "X-Banking-Response-Time"
              value: "%RESPONSE_DURATION%"
          - header:
              key: "Cache-Control"
              value: "no-store, no-cache, must-revalidate, private"

---
# Banking DDoS Protection
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: banking-ddos-protection
  namespace: istio-system
  labels:
    banking-component: ddos-protection
    compliance-level: fapi-2.0
spec:
  workloadSelector:
    labels:
      app: istio-proxy
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stats_config:
            stats_tags:
            - tag_name: banking_client_ip
              regex: "^cluster\\.(.+?)\\."
            - tag_name: banking_request_method
              regex: "^(\\w+)"
          use_remote_address: true
          xff_num_trusted_hops: 1