stages:
  - validate
  - contract
  - security

variables:
  CONTEXT_DIR: "."
  CONTEXT_README: "${CONTEXT_DIR}/README.md"
  CONTEXT_MANIFEST: "${CONTEXT_DIR}/REPO_MANIFEST.md"
  CONTEXT_OPENAPI: ""

validate_context_artifacts:
  stage: validate
  image: alpine:3.20
  script:
    - test -d "${CONTEXT_DIR}"
    - test -f "${CONTEXT_README}"
    - test -f "${CONTEXT_MANIFEST}"
    - test -f "${CONTEXT_OPENAPI}"

lint_openapi_contract:
  stage: contract
  image: node:20-alpine
  script:
    - npm install -g @redocly/cli@1.24.0
    - redocly lint "${CONTEXT_OPENAPI}"

secret_scan:
  stage: security
  image:
    name: zricethezav/gitleaks:v8.21.2
    entrypoint: [""]
  script:
    - gitleaks detect --no-git --source "${CONTEXT_DIR}" --exit-code 1
