global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Banking Application Metrics
  - job_name: 'banking-app'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['banking-app-enterprise:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: banking-app-enterprise:8080

  # PostgreSQL Exporter (if available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-enterprise:5432']
    scrape_interval: 30s

  # Redis Exporter (if available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-enterprise:6379']
    scrape_interval: 30s

  # Kafka Exporter (if available)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  # Keycloak Metrics (if available)
  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak:8080']
    scrape_interval: 30s

  # Nginx Gateway Metrics (if available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['api-gateway:80']
    scrape_interval: 30s