# Prometheus Configuration for UAT Environment
# Enterprise Loan Management System - User Acceptance Testing

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'uat'
    cluster: 'banking-uat'

rule_files:
  - "banking-alerts-uat.yml"

scrape_configs:
  # UAT Banking Application
  - job_name: 'uat-banking-app'
    static_configs:
      - targets: ['uat-banking-app:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: uat-banking-app:8080
    
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(jvm_|process_|system_|http_|banking_|loan_|payment_|customer_|cache_|security_|compliance_).*'
        action: keep

  # PostgreSQL Database Metrics
  - job_name: 'uat-postgres'
    static_configs:
      - targets: ['uat-database:5432']
    scrape_interval: 30s
    scrape_timeout: 10s
    
    relabel_configs:
      - target_label: database
        replacement: 'banking_uat'

  # Redis Cache Metrics  
  - job_name: 'uat-redis'
    static_configs:
      - targets: ['uat-redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s
    
    relabel_configs:
      - target_label: cache_instance
        replacement: 'uat-redis'

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

# Alerting Configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Storage Configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true