global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Enhanced Banking Application
  - job_name: 'banking-enhanced'
    static_configs:
      - targets: ['banking-app-enhanced:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Development Banking Application
  - job_name: 'banking-dev'
    static_configs:
      - targets: ['banking-app-dev:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Envoy Proxy Metrics
  - job_name: 'envoy-proxy'
    static_configs:
      - targets: ['envoy-proxy:9901']
    metrics_path: '/stats/prometheus'
    scrape_interval: 10s

  # PostgreSQL Exporter (if needed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Metrics (if redis exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']