apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-management-java21
  namespace: loan-management
  labels:
    app: loan-management
    version: java21
    tier: backend
    framework: spring-boot
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: loan-management
      version: java21
  template:
    metadata:
      labels:
        app: loan-management
        version: java21
        tier: backend
        framework: spring-boot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: loan-management-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: loan-management
        image: {{DOCKER_REGISTRY}}/loan-management:{{IMAGE_TAG}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 8081
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "{{DEPLOYMENT_ENV}},java21"
        - name: JAVA_OPTS
          value: "-XX:+UseZGC -XX:MaxGCPauseMillis=10 -Xms2g -Xmx8g --enable-preview -Djdk.virtualThreadScheduler.parallelism=32"
        # Database configuration
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: loan-management-db-secret
              key: jdbc-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: loan-management-db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: loan-management-db-secret
              key: password
        # Redis configuration
        - name: SPRING_DATA_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: loan-management-config
              key: redis.host
        - name: SPRING_DATA_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: loan-management-config
              key: redis.port
        # Java 21 specific configurations
        - name: VIRTUAL_THREADS_ENABLED
          value: "true"
        - name: PATTERN_MATCHING_OPTIMIZED
          value: "true"
        - name: SEQUENCED_COLLECTIONS_ENABLED
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "10Gi"
            cpu: "4000m"
            ephemeral-storage: "5Gi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health/startup
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
        - name: tmp-volume
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config-volume
        configMap:
          name: loan-management-config-java21
          defaultMode: 0440
      - name: logs-volume
        emptyDir:
          sizeLimit: 10Gi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 5Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - loan-management
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "java21"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: loan-management-service
  namespace: loan-management
  labels:
    app: loan-management
    version: java21
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: loan-management
    version: java21
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800