# Prometheus Configuration for Enterprise Banking System
# PCI-DSS v4 Compliant Monitoring with Enhanced Security

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'enterprise-loan-management'
    environment: '${ENVIRONMENT}'
    region: '${DATA_RESIDENCY}'
    compliance: 'pci-dss-v4'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      tls_config:
        ca_file: /etc/ssl/certs/ca.crt
        cert_file: /etc/ssl/certs/prometheus.crt
        key_file: /etc/ssl/private/prometheus.key
        insecure_skip_verify: false

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/*.yml"
  - "/etc/prometheus/alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Main application metrics
  - job_name: 'loan-management-app'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: 
          - 'host.docker.internal:8080'
    tls_config:
      ca_file: /etc/ssl/certs/ca.crt
      cert_file: /etc/ssl/certs/prometheus.crt
      key_file: /etc/ssl/private/prometheus.key
      insecure_skip_verify: false
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'host.docker.internal:8080'
    metric_relabel_configs:
      # Add data classification labels
      - source_labels: [__name__]
        regex: '.*_customer_.*'
        target_label: data_classification
        replacement: 'restricted'
      - source_labels: [__name__]
        regex: '.*_payment_.*|.*_card_.*'
        target_label: data_classification
        replacement: 'pci_dss'
      - source_labels: [__name__]
        regex: '.*_loan_.*|.*_transaction_.*'
        target_label: data_classification
        replacement: 'confidential'

  # Log Event Store Service
  - job_name: 'log-event-store'
    scrape_interval: 30s
    static_configs:
      - targets: ['log-event-store:8081']
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - target_label: service
        replacement: 'log-event-store'

  # Data Sovereignty Controller
  - job_name: 'data-sovereignty-controller'
    scrape_interval: 30s
    static_configs:
      - targets: ['data-sovereignty-controller:8082']
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - target_label: service
        replacement: 'data-sovereignty-controller'

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    scrape_interval: 30s
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: '/metrics'
    relabel_configs:
      - target_label: service
        replacement: 'otel-collector'

  # Infrastructure monitoring
  - job_name: 'elasticsearch'
    scrape_interval: 60s
    static_configs:
      - targets: ['elasticsearch-secure:9200']
    metrics_path: '/_prometheus/metrics'
    scheme: https
    basic_auth:
      username: '${ELASTICSEARCH_USERNAME}'
      password: '${ELASTICSEARCH_PASSWORD}'
    tls_config:
      ca_file: /etc/ssl/certs/ca.crt
      insecure_skip_verify: false

  - job_name: 'postgres-audit'
    scrape_interval: 60s
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - target_label: service
        replacement: 'postgres-audit'
      - target_label: data_classification
        replacement: 'restricted'

  - job_name: 'redis-logs'
    scrape_interval: 60s
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - target_label: service
        replacement: 'redis-logs'

  - job_name: 'kafka-secure'
    scrape_interval: 60s
    static_configs:
      - targets: ['kafka-exporter:9308']
    relabel_configs:
      - target_label: service
        replacement: 'kafka-secure'

  # JVM and system metrics
  - job_name: 'node-exporter'
    scrape_interval: 60s
    static_configs:
      - targets: 
          - 'node-exporter:9100'
    relabel_configs:
      - target_label: service
        replacement: 'system-metrics'

  # Docker container metrics
  - job_name: 'cadvisor'
    scrape_interval: 60s
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - target_label: service
        replacement: 'container-metrics'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

# Remote write configuration for multi-region setup
remote_write:
  - url: '${REMOTE_WRITE_ENDPOINT}'
    headers:
      X-Region: '${DATA_RESIDENCY}'
      X-Compliance-Level: 'PCI-DSS-v4'
    queue_config:
      max_samples_per_send: 1000
      max_shards: 10
      capacity: 10000
    write_relabel_configs:
      # Only send PCI-DSS relevant metrics to central store
      - source_labels: [data_classification]
        regex: 'pci_dss|restricted'
        action: keep
    tls_config:
      ca_file: /etc/ssl/certs/remote-ca.crt
      cert_file: /etc/ssl/certs/remote-client.crt
      key_file: /etc/ssl/private/remote-client.key

# Storage configuration
storage:
  tsdb:
    retention.time: 90d
    retention.size: 50GB
    wal-compression: true
    no-lockfile: false

# Security configuration
web:
  listen-address: ':9090'
  external-url: 'https://prometheus.banking.local'
  route-prefix: '/'
  enable-lifecycle: true
  enable-admin-api: true
  console.templates: '/etc/prometheus/consoles'
  console.libraries: '/etc/prometheus/console_libraries'