name: Feature request
description: Propose a new capability or enhancement
title: "[Feature]: "
labels:
  - enhancement
assignees: []
body:
  - type: input
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Corporate AIS does not expose scheduled payments reconciliation fields
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe expected behavior and scope
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] API contract updated
        - [ ] Unit tests >= 85% for affected module
        - [ ] Integration tests updated
    validations:
      required: true

