apiVersion: v1
kind: ConfigMap
metadata:
  name: amanahfi-platform-config
  namespace: amanahfi-platform
  labels:
    app.kubernetes.io/name: amanahfi-platform
    app.kubernetes.io/component: configmap
    app.kubernetes.io/part-of: amanahfi-ecosystem
    app.kubernetes.io/managed-by: kustomize
data:
  # Application configuration
  SPRING_PROFILES_ACTIVE: "production,kubernetes,amanahfi"
  SERVER_PORT: "8080"
  MANAGEMENT_SERVER_PORT: "8081"
  
  # Islamic Finance configuration
  ISLAMIC_FINANCE_ENABLED: "true"
  SHARIA_COMPLIANCE_MODE: "strict"
  SHARIA_BOARD_VALIDATION: "enabled"
  HALAL_ASSET_VERIFICATION: "mandatory"
  
  # CBDC configuration
  CBDC_INTEGRATION_ENABLED: "true"
  DIGITAL_DIRHAM_NETWORK: "production"
  CORDA_NETWORK_ENDPOINT: "https://corda-network.cbuae.gov.ae"
  
  # Regional and jurisdiction settings
  DEFAULT_JURISDICTION: "UAE"
  SUPPORTED_JURISDICTIONS: "UAE,SAU,QAT,KWT,BHR,OMN,TUR"
  DEFAULT_CURRENCY: "AED"
  CBDC_CURRENCIES: "AED-CBDC,SAR-CBDC,QAR-CBDC,KWD-CBDC,BHD-CBDC,OMR-CBDC"
  
  # Timezone and localization
  TZ: "Asia/Dubai"
  DEFAULT_LOCALE: "ar_AE"
  SUPPORTED_LOCALES: "ar_AE,en_US,ar_SA,en_GB"
  
  # Security configuration
  SECURITY_REQUIRE_SSL: "true"
  OAUTH2_ISSUER_URI: "https://iam.amanahfi.ae/auth/realms/amanahfi"
  DPOP_VALIDATION_ENABLED: "true"
  MTLS_ENABLED: "true"
  
  # Cache configuration
  REDIS_HOST: "redis-cluster.amanahfi-platform.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DATABASE: "0"
  REDIS_TIMEOUT: "2000"
  CACHE_TTL_DEFAULT: "1800"
  CACHE_TTL_ISLAMIC_FINANCE: "3600"
  CACHE_TTL_CBDC: "300"
  
  # Database configuration (connection details in secrets)
  DATABASE_POOL_SIZE: "20"
  DATABASE_CONNECTION_TIMEOUT: "30000"
  DATABASE_IDLE_TIMEOUT: "600000"
  DATABASE_MAX_LIFETIME: "1800000"
  
  # Kafka configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka-cluster.amanahfi-platform.svc.cluster.local:9092"
  KAFKA_CONSUMER_GROUP: "amanahfi-platform"
  KAFKA_TOPIC_PREFIX: "amanahfi"
  
  # Monitoring and observability
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  
  # Logging configuration
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_AMANAHFI: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  # API rate limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"
  RATE_LIMIT_BURST_CAPACITY: "2000"
  
  # External service timeouts
  EXTERNAL_SERVICE_TIMEOUT: "30000"
  REGULATORY_API_TIMEOUT: "45000"
  CORDA_NETWORK_TIMEOUT: "60000"
  
  # Compliance and regulatory
  COMPLIANCE_VALIDATION_ENABLED: "true"
  AML_SCREENING_ENABLED: "true"
  SANCTIONS_SCREENING_ENABLED: "true"
  KYC_VALIDATION_REQUIRED: "true"
  
  # Business rules
  MAX_TRANSACTION_AMOUNT: "1000000"
  MAX_DAILY_TRANSACTION_LIMIT: "5000000"
  CROSS_BORDER_REPORTING_THRESHOLD: "10000"
  
  # File upload limits
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "10MB"
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "50MB"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amanahfi-platform-regulatory-config
  namespace: amanahfi-platform
  labels:
    app.kubernetes.io/name: amanahfi-platform
    app.kubernetes.io/component: regulatory-config
    app.kubernetes.io/part-of: amanahfi-ecosystem
data:
  # CBUAE (Central Bank of UAE) configuration
  CBUAE_API_ENDPOINT: "https://api.centralbank.ae/regulatory"
  CBUAE_REPORTING_ENABLED: "true"
  CBUAE_AML_REPORTING: "enabled"
  CBUAE_SAR_THRESHOLD: "40000"
  CBUAE_CTR_THRESHOLD: "15000"
  
  # VARA (Virtual Assets Regulatory Authority) configuration
  VARA_API_ENDPOINT: "https://api.vara.ae/compliance"
  VARA_CBDC_REPORTING: "enabled"
  VARA_VA_TRANSACTION_REPORTING: "enabled"
  
  # HSA (Higher Sharia Authority) configuration
  HSA_API_ENDPOINT: "https://api.hsa.ae/sharia-compliance"
  HSA_FATWA_VALIDATION: "enabled"
  HSA_PRODUCT_APPROVAL_REQUIRED: "true"
  HSA_TRANSACTION_SCREENING: "enabled"
  
  # Regional regulatory endpoints
  SAMA_API_ENDPOINT: "https://api.sama.gov.sa/compliance"
  QCB_API_ENDPOINT: "https://api.qcb.gov.qa/regulatory"
  CBK_API_ENDPOINT: "https://api.cbk.gov.kw/compliance"
  CBB_API_ENDPOINT: "https://api.cbb.gov.bh/regulatory"
  CBO_API_ENDPOINT: "https://api.cbo-oman.org/compliance"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amanahfi-platform-islamic-finance-config
  namespace: amanahfi-platform
  labels:
    app.kubernetes.io/name: amanahfi-platform
    app.kubernetes.io/component: islamic-finance-config
    app.kubernetes.io/part-of: amanahfi-ecosystem
data:
  # Supported Islamic Finance products
  SUPPORTED_PRODUCTS: "MURABAHA,MUSHARAKAH,IJARAH,SALAM,ISTISNA,QARD_HASSAN"
  
  # Murabaha configuration
  MURABAHA_MIN_MARGIN: "0.01"
  MURABAHA_MAX_MARGIN: "0.30"
  MURABAHA_DEFAULT_MARGIN: "0.15"
  MURABAHA_MAX_TERM_MONTHS: "300"
  
  # Musharakah configuration
  MUSHARAKAH_MIN_PARTNER_SHARE: "0.10"
  MUSHARAKAH_MAX_PARTNER_SHARE: "0.90"
  MUSHARAKAH_PROFIT_SHARING_CALCULATION: "weighted_average"
  
  # Ijarah configuration
  IJARAH_MIN_TERM_MONTHS: "12"
  IJARAH_MAX_TERM_MONTHS: "120"
  IJARAH_OWNERSHIP_TRANSFER_ENABLED: "true"
  
  # Sharia compliance rules
  PROHIBITED_SECTORS: "ALCOHOL,GAMBLING,TOBACCO,PORK,CONVENTIONAL_INSURANCE,CONVENTIONAL_BANKING"
  DEBT_TO_ASSET_RATIO_LIMIT: "0.33"
  CASH_TO_ASSET_RATIO_LIMIT: "0.33"
  INTEREST_INCOME_LIMIT: "0.05"
  
  # Asset verification
  HALAL_ASSET_CATEGORIES: "REAL_ESTATE,VEHICLES,MACHINERY,COMMODITIES,PRECIOUS_METALS"
  ASSET_VERIFICATION_REQUIRED: "true"
  THIRD_PARTY_ASSET_VALUATION: "mandatory"
  
  # Profit distribution rules
  PROFIT_CALCULATION_METHOD: "diminishing_musharakah"
  LOSS_SHARING_PRINCIPLE: "capital_contribution_basis"
  PROFIT_DISTRIBUTION_FREQUENCY: "monthly"