apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: amanahfi-platform-hpa
  namespace: amanahfi-platform
  labels:
    app.kubernetes.io/name: amanahfi-platform
    app.kubernetes.io/instance: amanahfi-platform
    app.kubernetes.io/component: hpa
    app.kubernetes.io/part-of: amanahfi-ecosystem
    app.kubernetes.io/managed-by: kustomize
  annotations:
    description: "Horizontal Pod Autoscaler for AmanahFi Platform"
    autoscaling.kubernetes.io/behavior: "scaleUp,scaleDown"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amanahfi-platform
  
  minReplicas: 3
  maxReplicas: 20
  
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Custom metrics for Islamic Finance workloads
  - type: Pods
    pods:
      metric:
        name: islamic_finance_transactions_per_second
        selector:
          matchLabels:
            app.kubernetes.io/name: amanahfi-platform
      target:
        type: AverageValue
        averageValue: "100"
  
  # Custom metrics for CBDC workloads
  - type: Pods
    pods:
      metric:
        name: cbdc_transfers_per_second
        selector:
          matchLabels:
            app.kubernetes.io/name: amanahfi-platform
      target:
        type: AverageValue
        averageValue: "50"
  
  # Request rate metrics
  - type: Object
    object:
      metric:
        name: http_requests_per_second
        selector:
          matchLabels:
            app.kubernetes.io/name: amanahfi-platform
      target:
        type: Value
        value: "1000"
      describedObject:
        apiVersion: v1
        kind: Service
        name: amanahfi-platform
  
  # Response time metrics
  - type: Object
    object:
      metric:
        name: http_request_duration_p95
        selector:
          matchLabels:
            app.kubernetes.io/name: amanahfi-platform
      target:
        type: Value
        value: "500m"  # 500ms
      describedObject:
        apiVersion: v1
        kind: Service
        name: amanahfi-platform
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min

---
# Vertical Pod Autoscaler for resource optimization
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: amanahfi-platform-vpa
  namespace: amanahfi-platform
  labels:
    app.kubernetes.io/name: amanahfi-platform
    app.kubernetes.io/instance: amanahfi-platform
    app.kubernetes.io/component: vpa
    app.kubernetes.io/part-of: amanahfi-ecosystem
  annotations:
    description: "Vertical Pod Autoscaler for AmanahFi Platform resource optimization"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amanahfi-platform
  
  updatePolicy:
    updateMode: "Auto"  # Can be "Off", "Initial", "Recreation", or "Auto"
    
  resourcePolicy:
    containerPolicies:
    - containerName: amanahfi-platform
      minAllowed:
        cpu: "250m"
        memory: "512Mi"
      maxAllowed:
        cpu: "2000m"
        memory: "4Gi"
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
    
    - containerName: fluent-bit
      minAllowed:
        cpu: "25m"
        memory: "32Mi"
      maxAllowed:
        cpu: "100m"
        memory: "128Mi"
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
# Pod Disruption Budget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: amanahfi-platform-pdb
  namespace: amanahfi-platform
  labels:
    app.kubernetes.io/name: amanahfi-platform
    app.kubernetes.io/instance: amanahfi-platform
    app.kubernetes.io/component: pdb
    app.kubernetes.io/part-of: amanahfi-ecosystem
  annotations:
    description: "Pod Disruption Budget to ensure high availability during maintenance"
spec:
  minAvailable: 2  # Ensure at least 2 pods remain available during disruptions
  selector:
    matchLabels:
      app.kubernetes.io/name: amanahfi-platform
      app.kubernetes.io/instance: amanahfi-platform