openapi: 3.0.3
info:
  title: Banking Metadata Enrichment Service API
  version: 0.1.0
  description: Enriched metadata endpoints for transaction, account, party, and standing order context.
servers:
  - url: https://api.example.com/open-finance/v1
paths:
  /metadata/accounts/{AccountId}/transactions:
    get:
      summary: Retrieve transaction metadata
      operationId: getTransactionMetadata
      tags:
        - TransactionMetadata
      security:
        - bearerAuth: []
        - dpopAuth: []
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/DPoP'
        - $ref: '#/components/parameters/InteractionId'
        - $ref: '#/components/parameters/ConsentId'
        - $ref: '#/components/parameters/IfNoneMatch'
        - name: AccountId
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/FromBookingDateTime'
        - $ref: '#/components/parameters/ToBookingDateTime'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: Transaction metadata list
          headers:
            X-FAPI-Interaction-ID:
              schema:
                type: string
            X-OF-Cache:
              schema:
                type: string
            ETag:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionMetadataResponse'
        '304':
          description: Not modified
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /metadata/accounts/{AccountId}/parties:
    get:
      summary: Retrieve party metadata
      operationId: getPartyMetadata
      tags:
        - PartyMetadata
      security:
        - bearerAuth: []
        - dpopAuth: []
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/DPoP'
        - $ref: '#/components/parameters/InteractionId'
        - $ref: '#/components/parameters/ConsentId'
        - name: AccountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Party metadata list
          headers:
            X-FAPI-Interaction-ID:
              schema:
                type: string
            X-OF-Cache:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartiesMetadataResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /metadata/accounts/{AccountId}:
    get:
      summary: Retrieve account scheme metadata
      operationId: getAccountMetadata
      tags:
        - AccountMetadata
      security:
        - bearerAuth: []
        - dpopAuth: []
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/DPoP'
        - $ref: '#/components/parameters/InteractionId'
        - $ref: '#/components/parameters/ConsentId'
        - name: AccountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account metadata
          headers:
            X-FAPI-Interaction-ID:
              schema:
                type: string
            X-OF-Cache:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountMetadataResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /metadata/standing-orders:
    get:
      summary: Retrieve standing order metadata
      operationId: getStandingOrderMetadata
      tags:
        - StandingOrderMetadata
      security:
        - bearerAuth: []
        - dpopAuth: []
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/DPoP'
        - $ref: '#/components/parameters/InteractionId'
        - $ref: '#/components/parameters/ConsentId'
        - name: accountId
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: Standing order metadata list
          headers:
            X-FAPI-Interaction-ID:
              schema:
                type: string
            X-OF-Cache:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandingOrdersMetadataResponse'
components:
  parameters:
    Authorization:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
    DPoP:
      name: DPoP
      in: header
      required: true
      schema:
        type: string
    InteractionId:
      name: X-FAPI-Interaction-ID
      in: header
      required: true
      schema:
        type: string
    ConsentId:
      name: X-Consent-ID
      in: header
      required: true
      schema:
        type: string
    IfNoneMatch:
      name: If-None-Match
      in: header
      required: false
      schema:
        type: string
    FromBookingDateTime:
      name: fromBookingDateTime
      in: query
      required: false
      schema:
        type: string
        format: date-time
    ToBookingDateTime:
      name: toBookingDateTime
      in: query
      required: false
      schema:
        type: string
        format: date-time
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
    PageSize:
      name: pageSize
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 1000
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    dpopAuth:
      type: http
      scheme: bearer
  schemas:
    TransactionMetadataResponse:
      type: object
      properties:
        Data:
          type: object
          properties:
            Transaction:
              type: array
              items:
                $ref: '#/components/schemas/TransactionMetadata'
        Links:
          type: object
          properties:
            Self:
              type: string
            Next:
              type: string
        Meta:
          type: object
          properties:
            Page:
              type: integer
            PageSize:
              type: integer
            TotalPages:
              type: integer
            TotalRecords:
              type: integer
    TransactionMetadata:
      type: object
      properties:
        TransactionId:
          type: string
        AccountId:
          type: string
        BookingDateTime:
          type: string
          format: date-time
        Amount:
          $ref: '#/components/schemas/Amount'
        ChargeAmount:
          $ref: '#/components/schemas/Amount'
        MerchantDetails:
          type: object
          properties:
            Name:
              type: string
            CategoryCode:
              type: string
            GeoLocation:
              $ref: '#/components/schemas/GeoLocation'
        FxDetails:
          type: object
          nullable: true
          properties:
            ExchangeRate:
              type: string
            OriginalCurrency:
              type: string
            TargetCurrency:
              type: string
    PartiesMetadataResponse:
      type: object
      properties:
        Data:
          type: object
          properties:
            Party:
              type: array
              items:
                $ref: '#/components/schemas/PartyMetadata'
    PartyMetadata:
      type: object
      properties:
        AccountId:
          type: string
        FullLegalName:
          type: string
        KycStatus:
          type: string
        RelationshipStartDate:
          type: string
          format: date-time
    AccountMetadataResponse:
      type: object
      properties:
        Data:
          type: object
          properties:
            Account:
              $ref: '#/components/schemas/AccountMetadata'
    AccountMetadata:
      type: object
      properties:
        AccountId:
          type: string
        SchemeName:
          type: string
        SecondaryIdentification:
          type: string
    StandingOrdersMetadataResponse:
      type: object
      properties:
        Data:
          type: object
          properties:
            StandingOrder:
              type: array
              items:
                $ref: '#/components/schemas/StandingOrderMetadata'
        Links:
          type: object
          properties:
            Self:
              type: string
            Next:
              type: string
        Meta:
          type: object
          properties:
            Page:
              type: integer
            PageSize:
              type: integer
            TotalPages:
              type: integer
            TotalRecords:
              type: integer
    StandingOrderMetadata:
      type: object
      properties:
        StandingOrderId:
          type: string
        AccountId:
          type: string
        Frequency:
          type: string
        FirstPaymentDateTime:
          type: string
          format: date-time
        FinalPaymentDateTime:
          type: string
          format: date-time
        Amount:
          $ref: '#/components/schemas/Amount'
    Amount:
      type: object
      properties:
        Amount:
          type: string
        Currency:
          type: string
    GeoLocation:
      type: object
      properties:
        Latitude:
          type: number
          format: double
        Longitude:
          type: number
          format: double
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        interactionId:
          type: string
        timestamp:
          type: string
          format: date-time
