openapi: 3.0.3
info:
  title: Compliance Context Service API
  version: 0.1.0
servers:
  - url: https://api.example.com/compliance
paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
