openapi: 3.0.3
info:
  title: Loan Context Service API
  version: 0.1.0
servers:
  - url: https://api.example.com/loans
paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
