openapi: 3.0.3
info:
  title: Payment Context Service API
  version: 0.1.0
  license:
    name: Proprietary
    url: https://openfinance.example.com/license

servers:
  - url: https://api.sandbox.openfinance.ae/payments
paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
