# Production overlay for AmanahFi Platform
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: amanahfi-platform-production
  annotations:
    description: "Production overlay for AmanahFi Islamic Finance and CBDC Platform"
    environment: "production"
    version: "1.0.0"

# Base configuration
bases:
- ../../base

# Namespace for production
namespace: amanahfi-platform

# Production-specific labels
commonLabels:
  environment: production
  tier: production
  ae.amanahfi.environment: "production"
  ae.amanahfi.tier: "production"

# Production annotations
commonAnnotations:
  environment: "production"
  deployment.amanahfi.ae/environment: "production"
  monitoring.amanahfi.ae/enabled: "true"
  backup.amanahfi.ae/enabled: "true"
  compliance.amanahfi.ae/level: "strict"

# Production images with specific tags
images:
- name: amanahfi/platform
  newTag: "1.0.0"  # Use specific version tags in production
- name: fluent/fluent-bit
  newTag: "2.2.0"
- name: busybox
  newTag: "1.35.0"

# Production-specific resources
resources:
- production-configmap.yaml
- production-secrets.yaml
- network-policy.yaml
- pod-security-policy.yaml
- service-monitor.yaml
- prometheus-rules.yaml
- certificate.yaml

# Production patches
patches:
# Scale up for production load
- target:
    kind: Deployment
    name: amanahfi-platform
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 5

# Production resource requirements
- target:
    kind: Deployment
    name: amanahfi-platform
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "2Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "1000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "4Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "2000m"

# Production HPA settings
- target:
    kind: HorizontalPodAutoscaler
    name: amanahfi-platform-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 5
    - op: replace
      path: /spec/maxReplicas
      value: 50
    - op: replace
      path: /spec/metrics/0/resource/target/averageUtilization
      value: 60

# Production ingress settings
- target:
    kind: Ingress
    name: amanahfi-platform-ingress
  patch: |-
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1rate-limit
      value: "2000"
    - op: add
      path: /metadata/annotations/nginx.ingress.kubernetes.io~1rate-limit-burst
      value: "5000"

# Strategic merge patches
patchesStrategicMerge:
- production-deployment-patch.yaml
- production-service-patch.yaml

# JSON patches for fine-grained control
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: amanahfi-platform
  path: patches/production-deployment.yaml

# Production-specific replacements
replacements:
- source:
    kind: ConfigMap
    name: amanahfi-platform-production-config
    fieldPath: data.ENVIRONMENT
  targets:
  - select:
      kind: Deployment
      name: amanahfi-platform
    fieldPaths:
    - spec.template.spec.containers.[name=amanahfi-platform].env.[name=ENVIRONMENT].value

# Production secret generators (commented out - use external secret management)
# secretGenerator:
# - name: amanahfi-platform-production-secrets
#   literals:
#   - DATABASE_PASSWORD=${DATABASE_PASSWORD}
#   - REDIS_PASSWORD=${REDIS_PASSWORD}
#   type: Opaque

# Production ConfigMap generators
configMapGenerator:
- name: amanahfi-platform-production-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=INFO
  - SPRING_PROFILES_ACTIVE=production,kubernetes,amanahfi
  - METRICS_ENABLED=true
  - TRACING_ENABLED=true
  - SECURITY_LEVEL=high
  - COMPLIANCE_MODE=strict
  - RATE_LIMIT_REQUESTS_PER_MINUTE=2000
  - MAX_TRANSACTION_AMOUNT=10000000
  - CROSS_BORDER_REPORTING_THRESHOLD=10000
  behavior: merge

- name: fluent-bit-production-config
  files:
  - configs/fluent-bit-production.conf
  - configs/parsers-production.conf

# Disable name suffix hash for production (use versioned resources)
generatorOptions:
  disableNameSuffixHash: true
  labels:
    environment: production
    managed-by: kustomize-production
  annotations:
    config.kubernetes.io/production-config: "true"

# Production-specific transformers
transformers:
- transformers/production-security.yaml
- transformers/production-monitoring.yaml
- transformers/production-compliance.yaml

# Production validation
validators:
- kind: ValidatingAdmissionPolicy
  path: validators/production-resource-limits.yaml
- kind: ValidatingAdmissionPolicy
  path: validators/production-security-standards.yaml
- kind: ValidatingAdmissionPolicy
  path: validators/production-compliance-requirements.yaml