# Prometheus Alerting Rules for Banking System
# PCI-DSS v4 Compliant Security and Compliance Monitoring

groups:
  - name: "banking.security.alerts"
    interval: 30s
    rules:
      # Critical Security Alerts
      - alert: "SecurityBreach"
        expr: increase(security_events_total{severity="critical"}[5m]) > 0
        for: 0m
        labels:
          severity: "critical"
          compliance_framework: "PCI-DSS-v4"
          alert_type: "security"
          data_classification: "restricted"
        annotations:
          summary: "Critical security breach detected"
          description: "A critical security event has been detected: {{ $labels.event_type }}"
          remediation: "Immediate investigation required. Isolate affected systems."
          runbook_url: "https://runbooks.bank.com/security/breach-response"

      - alert: "PciDataExposure"
        expr: increase(pci_data_exposure_events_total[1m]) > 0
        for: 0m
        labels:
          severity: "critical"
          compliance_framework: "PCI-DSS-v4"
          alert_type: "compliance"
          data_classification: "pci_dss"
        annotations:
          summary: "PCI-DSS data exposure detected"
          description: "Potential PCI-DSS scope data exposure in {{ $labels.service }}"
          remediation: "Immediate containment required. Follow PCI incident response procedures."
          compliance_impact: "PCI-DSS violation - notify card brands within 72 hours"

      - alert: "UnauthorizedDataAccess"
        expr: increase(unauthorized_access_attempts_total[5m]) > 3
        for: 2m
        labels:
          severity: "high"
          alert_type: "security"
          data_classification: "confidential"
        annotations:
          summary: "Multiple unauthorized access attempts detected"
          description: "{{ $value }} unauthorized access attempts from {{ $labels.source_ip }}"
          remediation: "Block source IP and investigate user account"

      - alert: "AuditTrailTampering"
        expr: increase(audit_trail_integrity_violations_total[1m]) > 0
        for: 0m
        labels:
          severity: "critical"
          compliance_framework: "SOX"
          alert_type: "compliance"
        annotations:
          summary: "Audit trail integrity violation detected"
          description: "Potential tampering with audit logs detected"
          remediation: "Investigate immediately. Preserve evidence for forensic analysis."

  - name: "banking.compliance.alerts"
    interval: 60s
    rules:
      # Compliance Monitoring
      - alert: "GdprViolation"
        expr: increase(gdpr_violations_total[5m]) > 0
        for: 0m
        labels:
          severity: "high"
          compliance_framework: "GDPR"
          alert_type: "compliance"
          jurisdiction: "EU"
        annotations:
          summary: "GDPR compliance violation detected"
          description: "GDPR violation: {{ $labels.violation_type }}"
          remediation: "Investigate and remediate within 72 hours"
          legal_impact: "Potential regulatory fine and notification requirements"

      - alert: "DataResidencyViolation"
        expr: increase(data_residency_violations_total[1m]) > 0
        for: 0m
        labels:
          severity: "high"
          alert_type: "compliance"
        annotations:
          summary: "Data residency violation detected"
          description: "Data transferred outside permitted jurisdiction: {{ $labels.source_region }} -> {{ $labels.destination_region }}"
          remediation: "Stop data transfer and investigate data flow"

      - alert: "RetentionPolicyViolation"
        expr: increase(retention_policy_violations_total[1h]) > 0
        for: 5m
        labels:
          severity: "medium"
          alert_type: "compliance"
        annotations:
          summary: "Data retention policy violation"
          description: "Data retained beyond policy limits: {{ $labels.data_type }}"
          remediation: "Purge expired data and review retention policies"

  - name: "banking.performance.alerts"
    interval: 30s
    rules:
      # Performance and Availability
      - alert: "HighErrorRate"
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: "high"
          alert_type: "performance"
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} in {{ $labels.service }}"
          remediation: "Investigate application errors and system health"

      - alert: "LoggingSystemDown"
        expr: up{job="log-event-store"} == 0
        for: 1m
        labels:
          severity: "critical"
          alert_type: "system"
          compliance_impact: "audit_trail"
        annotations:
          summary: "Logging system is down"
          description: "Central logging system is unavailable"
          remediation: "Restore logging system immediately to maintain audit compliance"

      - alert: "DatabaseConnectionIssues"
        expr: increase(database_connection_errors_total[5m]) > 10
        for: 2m
        labels:
          severity: "high"
          alert_type: "infrastructure"
        annotations:
          summary: "Database connection issues detected"
          description: "{{ $value }} database connection errors in last 5 minutes"
          remediation: "Check database health and connection pool settings"

  - name: "banking.business.alerts"
    interval: 60s
    rules:
      # Business Logic Alerts
      - alert: "LargeTransactionDetected"
        expr: increase(large_transactions_total[1m]) > 0
        for: 0m
        labels:
          severity: "medium"
          alert_type: "business"
          data_classification: "confidential"
        annotations:
          summary: "Large transaction detected"
          description: "Transaction amount exceeds threshold: {{ $labels.amount }}"
          remediation: "Review transaction for fraud indicators"

      - alert: "FraudAlertTriggered"
        expr: increase(fraud_alerts_total[1m]) > 0
        for: 0m
        labels:
          severity: "high"
          alert_type: "fraud"
          data_classification: "restricted"
        annotations:
          summary: "Fraud alert triggered"
          description: "Suspicious activity detected: {{ $labels.fraud_type }}"
          remediation: "Investigate immediately and consider account restrictions"

      - alert: "UnusualTransactionPattern"
        expr: rate(transactions_total[1h]) > avg_over_time(rate(transactions_total[1h])[7d:1h]) * 3
        for: 15m
        labels:
          severity: "medium"
          alert_type: "business"
        annotations:
          summary: "Unusual transaction pattern detected"
          description: "Transaction rate is 3x above normal: {{ $value }}"
          remediation: "Monitor for potential fraud or system issues"

  - name: "banking.infrastructure.alerts"
    interval: 30s
    rules:
      # Infrastructure Monitoring
      - alert: "HighMemoryUsage"
        expr: process_resident_memory_bytes / 1024 / 1024 > 2048
        for: 5m
        labels:
          severity: "medium"
          alert_type: "infrastructure"
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}MB in {{ $labels.instance }}"
          remediation: "Monitor for memory leaks and consider scaling"

      - alert: "DiskSpaceRunningLow"
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.9
        for: 5m
        labels:
          severity: "high"
          alert_type: "infrastructure"
        annotations:
          summary: "Disk space running low"
          description: "Disk usage is above 90% on {{ $labels.device }}"
          remediation: "Free up disk space or provision additional storage"

      - alert: "ServiceDiscoveryIssues"
        expr: increase(service_discovery_failures_total[5m]) > 5
        for: 2m
        labels:
          severity: "medium"
          alert_type: "infrastructure"
        annotations:
          summary: "Service discovery issues detected"
          description: "{{ $value }} service discovery failures in last 5 minutes"
          remediation: "Check service registry and network connectivity"

  - name: "banking.data.alerts"
    interval: 60s
    rules:
      # Data Quality and Integrity
      - alert: "DataCorruptionDetected"
        expr: increase(data_corruption_events_total[5m]) > 0
        for: 0m
        labels:
          severity: "critical"
          alert_type: "data_integrity"
          compliance_impact: "audit_trail"
        annotations:
          summary: "Data corruption detected"
          description: "Data integrity check failed for {{ $labels.table }}"
          remediation: "Restore from backup and investigate root cause"

      - alert: "BackupFailure"
        expr: increase(backup_failures_total[1h]) > 0
        for: 0m
        labels:
          severity: "high"
          alert_type: "backup"
          compliance_impact: "business_continuity"
        annotations:
          summary: "Backup operation failed"
          description: "Backup failed for {{ $labels.backup_type }}"
          remediation: "Investigate backup system and ensure data protection"

      - alert: "DataMaskingFailure"
        expr: increase(data_masking_failures_total[5m]) > 0
        for: 0m
        labels:
          severity: "high"
          compliance_framework: "PCI-DSS-v4"
          alert_type: "compliance"
        annotations:
          summary: "Data masking failure detected"
          description: "Sensitive data masking failed in {{ $labels.service }}"
          remediation: "Investigate and ensure no sensitive data exposure"

  - name: "banking.regulatory.alerts"
    interval: 300s
    rules:
      # Regulatory Compliance
      - alert: "ComplianceReportingDelay"
        expr: time() - compliance_last_report_timestamp > 86400
        for: 1h
        labels:
          severity: "medium"
          alert_type: "compliance"
        annotations:
          summary: "Compliance reporting delayed"
          description: "{{ $labels.report_type }} report is overdue"
          remediation: "Generate missing compliance reports immediately"

      - alert: "RegulatoryChangeDetected"
        expr: increase(regulatory_updates_total[1d]) > 0
        for: 0m
        labels:
          severity: "low"
          alert_type: "regulatory"
        annotations:
          summary: "New regulatory requirement detected"
          description: "Regulatory update: {{ $labels.regulation }}"
          remediation: "Review and implement necessary compliance changes"

      - alert: "CrossBorderTransferAlert"
        expr: increase(cross_border_transfers_total{data_classification=~"pci_dss|restricted"}[1h]) > 0
        for: 0m
        labels:
          severity: "medium"
          alert_type: "compliance"
        annotations:
          summary: "Cross-border transfer of sensitive data"
          description: "Sensitive data transferred across borders: {{ $labels.source_country }} -> {{ $labels.dest_country }}"
          remediation: "Verify transfer compliance with data protection laws"