{{- range $context := list "apiGateway" "onboarding" "accounts" "payments" "murabaha" "compliance" }}
{{- $config := index $.Values $context }}
{{- if $config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $context }}-deployment
  labels:
    app: {{ $context }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $context }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $context }}
        release: {{ $.Release.Name }}
    spec:
      {{- with $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $context }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
          imagePullPolicy: {{ $config.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $config.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ $.Release.Name }}-postgresql:5432/amanahfi"
            - name: SPRING_DATASOURCE_USERNAME
              value: "amanahfi"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-postgresql
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ $.Release.Name }}-kafka:9092"
            - name: SPRING_REDIS_HOST
              value: "{{ $.Release.Name }}-redis-master"
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-redis
                  key: redis-password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml $config.resources | nindent 12 }}
{{- end }}
{{- end }}