{{- range $context := list "apiGateway" "onboarding" "accounts" "payments" "murabaha" "compliance" }}
{{- $config := index $.Values $context }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $context }}-service
  labels:
    app: {{ $context }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: {{ $config.service.type }}
  ports:
    - port: {{ $config.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $context }}
    release: {{ $.Release.Name }}
{{- end }}
{{- end }}