# Enterprise Loan Management System - Prometheus Alert Rules
# Banking-specific alerts for comprehensive monitoring

groups:
  # System Health Alerts
  - name: system.health
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          domain: infrastructure
          compliance: high
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute"
          runbook_url: "https://docs.banking.com/runbooks/service-down"

      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          domain: performance
          compliance: medium
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"
          runbook_url: "https://docs.banking.com/runbooks/high-cpu"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          domain: performance
          compliance: medium
        annotations:
          summary: "High memory usage detected on {{ $labels.instance }}"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"
          runbook_url: "https://docs.banking.com/runbooks/high-memory"

      - alert: DiskSpaceRunningOut
        expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100 < 15
        for: 5m
        labels:
          severity: warning
          domain: storage
          compliance: medium
        annotations:
          summary: "Disk space running out on {{ $labels.instance }}"
          description: "Disk space is below 15% on {{ $labels.instance }}"
          runbook_url: "https://docs.banking.com/runbooks/disk-space"

  # Banking Application Alerts
  - name: banking.application
    rules:
      - alert: LoanProcessingDown
        expr: up{job="loan-service"} == 0
        for: 30s
        labels:
          severity: critical
          domain: banking
          compliance: high
          business_impact: high
        annotations:
          summary: "Loan processing service is down"
          description: "Loan processing service is unavailable - no new loans can be processed"
          runbook_url: "https://docs.banking.com/runbooks/loan-service-down"

      - alert: PaymentServiceDown
        expr: up{job="payment-service"} == 0
        for: 30s
        labels:
          severity: critical
          domain: banking
          compliance: high
          business_impact: high
        annotations:
          summary: "Payment processing service is down"
          description: "Payment processing service is unavailable - no payments can be processed"
          runbook_url: "https://docs.banking.com/runbooks/payment-service-down"

      - alert: CustomerServiceDown
        expr: up{job="customer-service"} == 0
        for: 30s
        labels:
          severity: critical
          domain: banking
          compliance: high
          business_impact: high
        annotations:
          summary: "Customer service is down"
          description: "Customer service is unavailable - customer operations are affected"
          runbook_url: "https://docs.banking.com/runbooks/customer-service-down"

      - alert: HighLoanApplicationFailureRate
        expr: (rate(loan_application_failed_total[5m]) / rate(loan_application_total[5m])) * 100 > 5
        for: 2m
        labels:
          severity: warning
          domain: banking
          compliance: medium
          business_impact: medium
        annotations:
          summary: "High loan application failure rate"
          description: "Loan application failure rate is above 5% for the last 5 minutes"
          runbook_url: "https://docs.banking.com/runbooks/loan-failure-rate"

      - alert: HighPaymentFailureRate
        expr: (rate(payment_failed_total[5m]) / rate(payment_total[5m])) * 100 > 2
        for: 2m
        labels:
          severity: warning
          domain: banking
          compliance: medium
          business_impact: medium
        annotations:
          summary: "High payment failure rate"
          description: "Payment failure rate is above 2% for the last 5 minutes"
          runbook_url: "https://docs.banking.com/runbooks/payment-failure-rate"

  # Security Alerts
  - name: banking.security
    rules:
      - alert: HighFailedLoginAttempts
        expr: rate(security_failed_login_total[5m]) > 10
        for: 1m
        labels:
          severity: warning
          domain: security
          compliance: high
        annotations:
          summary: "High failed login attempts detected"
          description: "Failed login attempts are above 10 per minute - possible brute force attack"
          runbook_url: "https://docs.banking.com/runbooks/failed-logins"

      - alert: SuspiciousActivity
        expr: rate(security_suspicious_activity_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
          domain: security
          compliance: high
        annotations:
          summary: "Suspicious activity detected"
          description: "Suspicious activity has been detected in the banking system"
          runbook_url: "https://docs.banking.com/runbooks/suspicious-activity"

      - alert: UnauthorizedAccessAttempt
        expr: rate(security_unauthorized_access_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
          domain: security
          compliance: high
        annotations:
          summary: "Unauthorized access attempt detected"
          description: "Unauthorized access attempts have been detected"
          runbook_url: "https://docs.banking.com/runbooks/unauthorized-access"

      - alert: TokenValidationFailure
        expr: (rate(oauth_token_validation_failed_total[5m]) / rate(oauth_token_validation_total[5m])) * 100 > 5
        for: 2m
        labels:
          severity: warning
          domain: security
          compliance: high
        annotations:
          summary: "High OAuth token validation failure rate"
          description: "OAuth token validation failure rate is above 5%"
          runbook_url: "https://docs.banking.com/runbooks/token-validation"

      - alert: DPoPValidationFailure
        expr: (rate(dpop_validation_failed_total[5m]) / rate(dpop_validation_total[5m])) * 100 > 3
        for: 2m
        labels:
          severity: warning
          domain: security
          compliance: high
        annotations:
          summary: "High DPoP validation failure rate"
          description: "DPoP validation failure rate is above 3%"
          runbook_url: "https://docs.banking.com/runbooks/dpop-validation"

  # Compliance Alerts
  - name: banking.compliance
    rules:
      - alert: ComplianceCheckFailure
        expr: rate(compliance_check_failed_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
          domain: compliance
          compliance: high
        annotations:
          summary: "Compliance check failure detected"
          description: "Compliance check has failed - immediate attention required"
          runbook_url: "https://docs.banking.com/runbooks/compliance-failure"

      - alert: KYCProcessingDelay
        expr: histogram_quantile(0.95, rate(kyc_processing_duration_seconds_bucket[5m])) > 300
        for: 5m
        labels:
          severity: warning
          domain: compliance
          compliance: high
        annotations:
          summary: "KYC processing delay detected"
          description: "95th percentile of KYC processing time is above 5 minutes"
          runbook_url: "https://docs.banking.com/runbooks/kyc-delay"

      - alert: AMLScanFailure
        expr: rate(aml_scan_failed_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
          domain: compliance
          compliance: high
        annotations:
          summary: "AML scan failure detected"
          description: "AML scanning has failed - compliance risk"
          runbook_url: "https://docs.banking.com/runbooks/aml-failure"

      - alert: RegulatoryReportingDelay
        expr: time() - regulatory_report_last_submission_timestamp > 86400
        for: 0s
        labels:
          severity: critical
          domain: compliance
          compliance: high
        annotations:
          summary: "Regulatory reporting delay"
          description: "Regulatory report has not been submitted for more than 24 hours"
          runbook_url: "https://docs.banking.com/runbooks/regulatory-delay"

  # Performance Alerts
  - name: banking.performance
    rules:
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          domain: performance
          compliance: medium
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 2 seconds"
          runbook_url: "https://docs.banking.com/runbooks/high-response-time"

      - alert: DatabaseConnectionPoolExhaustion
        expr: database_connection_pool_active / database_connection_pool_max > 0.9
        for: 2m
        labels:
          severity: warning
          domain: database
          compliance: medium
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "Database connection pool is 90% utilized"
          runbook_url: "https://docs.banking.com/runbooks/connection-pool"

      - alert: HighDatabaseQueryTime
        expr: histogram_quantile(0.95, rate(database_query_duration_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
          domain: database
          compliance: medium
        annotations:
          summary: "High database query time detected"
          description: "95th percentile database query time is above 5 seconds"
          runbook_url: "https://docs.banking.com/runbooks/slow-queries"

  # ML and Fraud Detection Alerts
  - name: banking.ml
    rules:
      - alert: FraudDetectionModelDown
        expr: up{job="ml-anomaly-service"} == 0
        for: 1m
        labels:
          severity: critical
          domain: ml
          compliance: high
          business_impact: high
        annotations:
          summary: "Fraud detection model is down"
          description: "ML fraud detection service is unavailable"
          runbook_url: "https://docs.banking.com/runbooks/fraud-model-down"

      - alert: HighFraudScore
        expr: fraud_detection_score > 0.8
        for: 0s
        labels:
          severity: critical
          domain: ml
          compliance: high
        annotations:
          summary: "High fraud score detected"
          description: "Transaction with fraud score above 0.8 detected"
          runbook_url: "https://docs.banking.com/runbooks/high-fraud-score"

      - alert: MLModelAccuracyDrop
        expr: ml_model_accuracy < 0.85
        for: 5m
        labels:
          severity: warning
          domain: ml
          compliance: medium
        annotations:
          summary: "ML model accuracy drop detected"
          description: "ML model accuracy has dropped below 85%"
          runbook_url: "https://docs.banking.com/runbooks/model-accuracy"

      - alert: AnomalyDetectionSpike
        expr: rate(anomaly_detection_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          domain: ml
          compliance: medium
        annotations:
          summary: "Anomaly detection spike"
          description: "Anomaly detection rate is above 10 per minute"
          runbook_url: "https://docs.banking.com/runbooks/anomaly-spike"

  # Infrastructure Alerts
  - name: banking.infrastructure
    rules:
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 30s
        labels:
          severity: critical
          domain: infrastructure
          compliance: high
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL database is not responding"
          runbook_url: "https://docs.banking.com/runbooks/postgres-down"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 30s
        labels:
          severity: critical
          domain: infrastructure
          compliance: high
        annotations:
          summary: "Redis cache is down"
          description: "Redis cache is not responding"
          runbook_url: "https://docs.banking.com/runbooks/redis-down"

      - alert: KafkaDown
        expr: up{job="kafka"} == 0
        for: 30s
        labels:
          severity: critical
          domain: infrastructure
          compliance: high
        annotations:
          summary: "Kafka message broker is down"
          description: "Kafka message broker is not responding"
          runbook_url: "https://docs.banking.com/runbooks/kafka-down"

      - alert: KeycloakDown
        expr: up{job="keycloak"} == 0
        for: 30s
        labels:
          severity: critical
          domain: infrastructure
          compliance: high
        annotations:
          summary: "Keycloak identity provider is down"
          description: "Keycloak identity provider is not responding"
          runbook_url: "https://docs.banking.com/runbooks/keycloak-down"

      - alert: HighKafkaConsumerLag
        expr: kafka_consumer_lag > 1000
        for: 5m
        labels:
          severity: warning
          domain: infrastructure
          compliance: medium
        annotations:
          summary: "High Kafka consumer lag detected"
          description: "Kafka consumer lag is above 1000 messages"
          runbook_url: "https://docs.banking.com/runbooks/kafka-lag"

  # Business Logic Alerts
  - name: banking.business
    rules:
      - alert: LoanApprovalRateDrop
        expr: (rate(loan_approved_total[1h]) / rate(loan_application_total[1h])) < 0.6
        for: 10m
        labels:
          severity: warning
          domain: business
          compliance: medium
        annotations:
          summary: "Loan approval rate drop detected"
          description: "Loan approval rate has dropped below 60%"
          runbook_url: "https://docs.banking.com/runbooks/loan-approval-drop"

      - alert: HighLoanDefaultRate
        expr: (rate(loan_defaulted_total[24h]) / rate(loan_disbursed_total[24h])) > 0.02
        for: 1h
        labels:
          severity: critical
          domain: business
          compliance: high
        annotations:
          summary: "High loan default rate detected"
          description: "Loan default rate is above 2% in the last 24 hours"
          runbook_url: "https://docs.banking.com/runbooks/high-default-rate"

      - alert: PaymentProcessingVolumeSpike
        expr: rate(payment_total[5m]) > 1000
        for: 2m
        labels:
          severity: warning
          domain: business
          compliance: medium
        annotations:
          summary: "Payment processing volume spike"
          description: "Payment processing volume is above 1000 per minute"
          runbook_url: "https://docs.banking.com/runbooks/payment-volume-spike"

  # Federation Monitoring Alerts
  - name: banking.federation
    rules:
      - alert: CrossRegionLatencyHigh
        expr: histogram_quantile(0.95, rate(cross_region_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          domain: federation
          compliance: medium
        annotations:
          summary: "High cross-region latency detected"
          description: "95th percentile cross-region latency is above 1 second"
          runbook_url: "https://docs.banking.com/runbooks/cross-region-latency"

      - alert: RegionFailoverRequired
        expr: region_health_status == 0
        for: 1m
        labels:
          severity: critical
          domain: federation
          compliance: high
        annotations:
          summary: "Region failover required"
          description: "Region {{ $labels.region }} is unhealthy - failover may be required"
          runbook_url: "https://docs.banking.com/runbooks/region-failover"

      - alert: DisasterRecoveryCheckFailed
        expr: disaster_recovery_check_status == 0
        for: 0s
        labels:
          severity: critical
          domain: federation
          compliance: high
        annotations:
          summary: "Disaster recovery check failed"
          description: "Disaster recovery check has failed for region {{ $labels.region }}"
          runbook_url: "https://docs.banking.com/runbooks/dr-check-failed"

      - alert: ReplicationLagHigh
        expr: replication_lag_seconds > 10
        for: 5m
        labels:
          severity: warning
          domain: federation
          compliance: medium
        annotations:
          summary: "High replication lag detected"
          description: "Replication lag is above 10 seconds between regions"
          runbook_url: "https://docs.banking.com/runbooks/replication-lag"