apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-loan-system
  namespace: argocd
  labels:
    app.kubernetes.io/name: enterprise-loan-system
    app.kubernetes.io/part-of: banking-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: banking-platform
  source:
    repoURL: https://github.com/your-org/enterprise-loan-system-gitops
    targetRevision: main
    path: applications/production/enterprise-loan-system
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-loan-system-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: monitoring-stack
    app.kubernetes.io/part-of: banking-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: banking-platform
  source:
    repoURL: https://github.com/your-org/enterprise-loan-system-gitops
    targetRevision: main
    path: applications/production/monitoring
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: banking-platform
  namespace: argocd
spec:
  description: Banking Platform Applications
  sourceRepos:
    - 'https://github.com/your-org/enterprise-loan-system*'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
  destinations:
    - namespace: banking-system*
      server: https://kubernetes.default.svc
    - namespace: monitoring*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: networking.k8s.io
      kind: Ingress
    - group: storage.k8s.io
      kind: StorageClass
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: monitoring.coreos.com
      kind: ServiceMonitor
  roles:
    - name: banking-developers
      description: Banking platform developers
      policies:
        - p, proj:banking-platform:banking-developers, applications, get, banking-platform/*, allow
        - p, proj:banking-platform:banking-developers, applications, sync, banking-platform/*, allow
      groups:
        - banking-platform:developers
    - name: banking-operators
      description: Banking platform operators
      policies:
        - p, proj:banking-platform:banking-operators, applications, *, banking-platform/*, allow
        - p, proj:banking-platform:banking-operators, repositories, *, *, allow
      groups:
        - banking-platform:operators