apiVersion: v2
name: amanahfi-platform
description: A Helm chart for AmanahFi Islamic Banking Platform
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - islamic-banking
  - fintech
  - microservices
  - spring-boot

home: https://github.com/amanahfi/platform
sources:
  - https://github.com/amanahfi/platform

maintainers:
  - name: AmanahFi Team
    email: platform@amanahfi.com

dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: kafka
    version: "25.3.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: redis
    version: "18.1.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled