apiVersion: v2
name: amanahfi-platform
description: A Helm chart for AmanahFi Islamic Banking Platform
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - islamic-banking
  - fintech
  - microservices
  - spring-boot

home: https://github.com/COPUR/enterprise-loan-management-system
sources:
  - https://github.com/COPUR/enterprise-loan-management-system

maintainers:
  - name: Ali Copur
    email: linkedin.com/in/acopur

dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: kafka
    version: "25.3.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: redis
    version: "18.1.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled