apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: amanahfi-platform
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: rules
    app.kubernetes.io/part-of: monitoring
data:
  amanahfi-platform.yml: |
    groups:
    - name: amanahfi-platform.rules
      interval: 30s
      rules:
      # Application availability
      - alert: AmanahFiPlatformDown
        expr: up{job="amanahfi-platform"} == 0
        for: 1m
        labels:
          severity: critical
          service: amanahfi-platform
          team: platform
        annotations:
          summary: "AmanahFi Platform is down"
          description: "AmanahFi Platform has been down for more than 1 minute. Instance: {{ $labels.instance }}"
          runbook_url: "https://docs.amanahfi.ae/runbooks/platform-down"
          
      # High error rate
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_server_requests_seconds_count{job="amanahfi-platform",status=~"5.."}[5m])) /
            sum(rate(http_server_requests_seconds_count{job="amanahfi-platform"}[5m]))
          ) * 100 > 5
        for: 5m
        labels:
          severity: critical
          service: amanahfi-platform
          team: platform
        annotations:
          summary: "High HTTP error rate detected"
          description: "Error rate is {{ $value }}% for the last 5 minutes"
          runbook_url: "https://docs.amanahfi.ae/runbooks/high-error-rate"

      # High response time
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95, 
            sum(rate(http_server_requests_seconds_bucket{job="amanahfi-platform"}[5m])) by (le)
          ) > 1
        for: 5m
        labels:
          severity: warning
          service: amanahfi-platform
          team: platform
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s"
          runbook_url: "https://docs.amanahfi.ae/runbooks/high-response-time"

      # High memory usage
      - alert: HighMemoryUsage
        expr: |
          (
            container_memory_working_set_bytes{container="amanahfi-platform"} /
            container_spec_memory_limit_bytes{container="amanahfi-platform"}
          ) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: amanahfi-platform
          team: platform
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% on instance {{ $labels.instance }}"
          runbook_url: "https://docs.amanahfi.ae/runbooks/high-memory-usage"

      # High CPU usage
      - alert: HighCPUUsage
        expr: |
          (
            rate(container_cpu_usage_seconds_total{container="amanahfi-platform"}[5m]) /
            container_spec_cpu_quota{container="amanahfi-platform"} * container_spec_cpu_period{container="amanahfi-platform"}
          ) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: amanahfi-platform
          team: platform
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on instance {{ $labels.instance }}"
          runbook_url: "https://docs.amanahfi.ae/runbooks/high-cpu-usage"

    - name: islamic-finance.rules
      interval: 30s
      rules:
      # Sharia compliance failure
      - alert: ShariaComplianceFailure
        expr: |
          increase(islamic_finance_sharia_compliance_failures_total[5m]) > 0
        for: 0s  # Alert immediately on any failure
        labels:
          severity: critical
          service: amanahfi-platform
          team: islamic-finance
          compliance: sharia
        annotations:
          summary: "Sharia compliance failure detected"
          description: "{{ $value }} Sharia compliance failures in the last 5 minutes"
          runbook_url: "https://docs.amanahfi.ae/runbooks/sharia-compliance-failure"
          compliance_team: "hsa-board@amanahfi.ae"

      # High Islamic Finance transaction failure rate
      - alert: HighIslamicFinanceFailureRate
        expr: |
          (
            sum(rate(islamic_finance_transactions_total{status="failed"}[5m])) /
            sum(rate(islamic_finance_transactions_total[5m]))
          ) * 100 > 2
        for: 5m
        labels:
          severity: warning
          service: amanahfi-platform
          team: islamic-finance
        annotations:
          summary: "High Islamic Finance transaction failure rate"
          description: "Islamic Finance transaction failure rate is {{ $value }}%"
          runbook_url: "https://docs.amanahfi.ae/runbooks/islamic-finance-failures"

      # Murabaha profit margin violation
      - alert: MurabahaProfitMarginViolation
        expr: |
          islamic_finance_murabaha_profit_margin > 0.30
        for: 0s
        labels:
          severity: critical
          service: amanahfi-platform
          team: islamic-finance
          compliance: sharia
        annotations:
          summary: "Murabaha profit margin violation"
          description: "Murabaha profit margin is {{ $value }}, exceeding Sharia-compliant limit of 30%"
          runbook_url: "https://docs.amanahfi.ae/runbooks/profit-margin-violation"

      # Low Islamic Finance transaction volume
      - alert: LowIslamicFinanceVolume
        expr: |
          sum(rate(islamic_finance_transactions_total[1h])) < 10
        for: 1h
        labels:
          severity: warning
          service: amanahfi-platform
          team: business
        annotations:
          summary: "Low Islamic Finance transaction volume"
          description: "Islamic Finance transaction rate is {{ $value }} transactions per second over the last hour"
          runbook_url: "https://docs.amanahfi.ae/runbooks/low-transaction-volume"

    - name: cbdc.rules
      interval: 30s
      rules:
      # CBDC network connectivity issues
      - alert: CBDCNetworkConnectivityIssue
        expr: |
          cbdc_corda_network_connectivity == 0
        for: 2m
        labels:
          severity: critical
          service: amanahfi-platform
          team: cbdc
          network: corda
        annotations:
          summary: "CBDC Corda network connectivity issue"
          description: "Unable to connect to Corda network for {{ $value }} minutes"
          runbook_url: "https://docs.amanahfi.ae/runbooks/corda-connectivity"
          escalation: "cbuae-tech-support@cbuae.gov.ae"

      # High CBDC transaction failure rate
      - alert: HighCBDCTransactionFailureRate
        expr: |
          (
            sum(rate(cbdc_transactions_total{status="failed"}[5m])) /
            sum(rate(cbdc_transactions_total[5m]))
          ) * 100 > 1
        for: 5m
        labels:
          severity: warning
          service: amanahfi-platform
          team: cbdc
        annotations:
          summary: "High CBDC transaction failure rate"
          description: "CBDC transaction failure rate is {{ $value }}%"
          runbook_url: "https://docs.amanahfi.ae/runbooks/cbdc-failures"

      # Digital Dirham balance discrepancy
      - alert: DigitalDirhamBalanceDiscrepancy
        expr: |
          abs(cbdc_wallet_balance_local - cbdc_wallet_balance_corda) > 0.01
        for: 1m
        labels:
          severity: critical
          service: amanahfi-platform
          team: cbdc
          compliance: cbuae
        annotations:
          summary: "Digital Dirham balance discrepancy detected"
          description: "Balance discrepancy of {{ $value }} AED-CBDC detected between local and Corda records"
          runbook_url: "https://docs.amanahfi.ae/runbooks/balance-discrepancy"

      # CBDC transaction processing delay
      - alert: CBDCTransactionProcessingDelay
        expr: |
          histogram_quantile(0.95, 
            sum(rate(cbdc_transaction_processing_duration_seconds_bucket[5m])) by (le)
          ) > 30
        for: 5m
        labels:
          severity: warning
          service: amanahfi-platform
          team: cbdc
        annotations:
          summary: "CBDC transaction processing delay"
          description: "95th percentile CBDC transaction processing time is {{ $value }} seconds"
          runbook_url: "https://docs.amanahfi.ae/runbooks/cbdc-processing-delay"

    - name: regulatory-compliance.rules
      interval: 30s
      rules:
      # Regulatory API failures
      - alert: RegulatoryAPIFailure
        expr: |
          increase(regulatory_api_requests_total{status=~"5.."}[5m]) > 0
        for: 0s
        labels:
          severity: critical
          service: amanahfi-platform
          team: compliance
        annotations:
          summary: "Regulatory API failure detected"
          description: "{{ $value }} failures to regulatory API {{ $labels.api_name }} in the last 5 minutes"
          runbook_url: "https://docs.amanahfi.ae/runbooks/regulatory-api-failure"

      # AML screening failure
      - alert: AMLScreeningFailure
        expr: |
          increase(aml_screening_failures_total[5m]) > 0
        for: 0s
        labels:
          severity: critical
          service: amanahfi-platform
          team: compliance
          compliance: aml
        annotations:
          summary: "AML screening failure detected"
          description: "{{ $value }} AML screening failures in the last 5 minutes"
          runbook_url: "https://docs.amanahfi.ae/runbooks/aml-screening-failure"
          escalation: "compliance-team@amanahfi.ae"

      # Sanctions screening alert
      - alert: SanctionsScreeningAlert
        expr: |
          increase(sanctions_screening_hits_total[1m]) > 0
        for: 0s
        labels:
          severity: critical
          service: amanahfi-platform
          team: compliance
          compliance: sanctions
        annotations:
          summary: "Sanctions screening hit detected"
          description: "{{ $value }} sanctions screening hits detected"
          runbook_url: "https://docs.amanahfi.ae/runbooks/sanctions-screening"
          escalation: "compliance-team@amanahfi.ae,legal-team@amanahfi.ae"

      # High SAR (Suspicious Activity Report) generation
      - alert: HighSARGeneration
        expr: |
          increase(suspicious_activity_reports_total[1h]) > 5
        for: 0s
        labels:
          severity: warning
          service: amanahfi-platform
          team: compliance
          compliance: sar
        annotations:
          summary: "High SAR generation rate"
          description: "{{ $value }} SARs generated in the last hour"
          runbook_url: "https://docs.amanahfi.ae/runbooks/high-sar-generation"

    - name: infrastructure.rules
      interval: 30s
      rules:
      # Database connection pool exhaustion
      - alert: DatabaseConnectionPoolExhaustion
        expr: |
          (
            hikaricp_connections_active{pool="HikariPool-1"} /
            hikaricp_connections_max{pool="HikariPool-1"}
          ) * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: amanahfi-platform
          team: platform
          component: database
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "Database connection pool usage is {{ $value }}%"
          runbook_url: "https://docs.amanahfi.ae/runbooks/db-connection-pool"

      # Redis cache hit rate too low
      - alert: LowRedisCacheHitRate
        expr: |
          (
            sum(rate(redis_cache_hits_total[5m])) /
            (sum(rate(redis_cache_hits_total[5m])) + sum(rate(redis_cache_misses_total[5m])))
          ) * 100 < 80
        for: 10m
        labels:
          severity: warning
          service: amanahfi-platform
          team: platform
          component: cache
        annotations:
          summary: "Low Redis cache hit rate"
          description: "Redis cache hit rate is {{ $value }}%"
          runbook_url: "https://docs.amanahfi.ae/runbooks/low-cache-hit-rate"

      # Kafka consumer lag
      - alert: KafkaConsumerLag
        expr: |
          kafka_consumer_lag_sum{topic=~"amanahfi.*"} > 1000
        for: 5m
        labels:
          severity: warning
          service: amanahfi-platform
          team: platform
          component: messaging
        annotations:
          summary: "High Kafka consumer lag"
          description: "Kafka consumer lag is {{ $value }} messages for topic {{ $labels.topic }}"
          runbook_url: "https://docs.amanahfi.ae/runbooks/kafka-consumer-lag"

      # Disk space low
      - alert: DiskSpaceLow
        expr: |
          (
            node_filesystem_avail_bytes{fstype!="tmpfs"} /
            node_filesystem_size_bytes{fstype!="tmpfs"}
          ) * 100 < 10
        for: 5m
        labels:
          severity: critical
          service: infrastructure
          team: platform
          component: storage
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value }}% available on {{ $labels.instance }}"
          runbook_url: "https://docs.amanahfi.ae/runbooks/low-disk-space"