apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: POST
    secureJsonData: {}

  - name: Elasticsearch-Logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "banking-*"
    editable: false
    jsonData:
      interval: "5s"
      timeField: "@timestamp"
      esVersion: "8.8.0"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"
    secureJsonData: {}

  - name: Elasticsearch-Compliance
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "banking-compliance-*"
    editable: false
    jsonData:
      interval: "30s"
      timeField: "@timestamp"
      esVersion: "8.8.0"
      maxConcurrentShardRequests: 5
    secureJsonData: {}

  - name: Elasticsearch-Security
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "security-incidents-*"
    editable: false
    jsonData:
      interval: "5s"
      timeField: "@timestamp"
      esVersion: "8.8.0"
      maxConcurrentShardRequests: 5
    secureJsonData: {}