apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-app-config
  namespace: banking-system
  labels:
    app: enterprise-loan-system
data:
  application.properties: |
    # Banking System Configuration
    spring.application.name=enterprise-loan-system
    server.port=5000
    
    # Database Configuration
    spring.datasource.url=jdbc:postgresql://banking-postgres:5432/banking_system
    spring.datasource.username=postgres
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=validate
    
    # Redis Configuration
    spring.redis.host=banking-redis
    spring.redis.port=6379
    spring.redis.timeout=2000ms
    spring.redis.jedis.pool.max-active=8
    spring.redis.jedis.pool.max-idle=8
    spring.redis.jedis.pool.min-idle=0
    
    # Banking Specific Configuration
    banking.loan.installments.allowed=6,9,12,24
    banking.interest.rate.min=0.1
    banking.interest.rate.max=0.5
    banking.compliance.tdd.required=75
    banking.fapi.security.enabled=true
    
    # Monitoring Configuration
    management.endpoints.web.exposure.include=health,metrics,prometheus
    management.endpoint.health.show-details=always
    management.metrics.export.prometheus.enabled=true
    
    # Logging Configuration
    logging.level.com.bank.loanmanagement=INFO
    logging.level.org.springframework.security=DEBUG
    logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: banking-system
  labels:
    app: postgres
data:
  POSTGRES_DB: banking_system
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: banking-system
  labels:
    app: redis
data:
  redis.conf: |
    # Redis Banking Configuration
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    timeout 300
    tcp-keepalive 60
    save 900 1
    save 300 10
    save 60 10000
    
    # Security
    requirepass banking_redis_password
    
    # Performance
    tcp-backlog 511
    databases 16
    
    # Logging
    loglevel notice