apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-app-config
  namespace: banking-system
  labels:
    app: enterprise-loan-system
    version: "1.0.0"
    environment: production
    compliance: banking
data:
  # 12-Factor App Configuration for Enterprise Banking System
  # All configuration externalized and environment-specific
  application.properties: |
    # Application Information (12-Factor: Build, Release, Run)
    app.name=Enterprise Loan Management System
    app.version=1.0.0
    app.description=Enterprise Banking System with Microservices Architecture
    
    # Server Configuration (12-Factor: Port Binding)
    server.port=8080
    server.servlet.context-path=/api
    server.compression.enabled=true
    server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
    
    # Spring Boot Configuration
    spring.application.name=enterprise-loan-management-system
    spring.profiles.active=production,kubernetes
    spring.main.allow-bean-definition-overriding=true
    
    # JPA Configuration (12-Factor: Backing Services)
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.format_sql=false
    spring.jpa.properties.hibernate.use_sql_comments=false
    
    # Banking Domain Configuration (12-Factor: Config)
    banking.loan.max-amount=5000000
    banking.loan.min-amount=1000
    banking.loan.max-term-months=360
    banking.loan.min-term-months=6
    banking.interest.min-rate=0.001
    banking.interest.max-rate=0.30
    banking.transaction.daily-limit=50000
    banking.transaction.monthly-limit=500000
    
    # Compliance Configuration
    banking.compliance.fapi.enabled=true
    banking.compliance.pci.enabled=true
    banking.compliance.audit.enabled=true
    banking.compliance.kyc.required=true
    
    # Performance Configuration
    banking.performance.cache.ttl=3600
    banking.performance.connection.timeout=5000
    banking.performance.read.timeout=10000
    banking.performance.max.concurrent.requests=100
    
    # Circuit Breaker Configuration
    resilience4j.circuitbreaker.instances.credit-bureau.failure-rate-threshold=50
    resilience4j.circuitbreaker.instances.credit-bureau.wait-duration-in-open-state=30s
    resilience4j.circuitbreaker.instances.credit-bureau.sliding-window-size=10
    
    # Rate Limiting Configuration
    resilience4j.ratelimiter.instances.api.limit-for-period=100
    resilience4j.ratelimiter.instances.api.limit-refresh-period=1s
    resilience4j.ratelimiter.instances.api.timeout-duration=0
    
    # Retry Configuration
    resilience4j.retry.instances.default.max-attempts=3
    resilience4j.retry.instances.default.wait-duration=1s
    
    # Monitoring Configuration (12-Factor: Admin Processes)
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=always
    management.endpoint.health.probes.enabled=true
    management.metrics.export.prometheus.enabled=true
    
    # Logging Configuration (12-Factor: Logs)
    logging.level.com.bank.loanmanagement=INFO
    logging.level.org.springframework=INFO
    logging.level.org.hibernate=WARN
    logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
    logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
    
    # Feature Flags (12-Factor: Config)
    banking.features.nlp.enabled=false
    banking.features.ai.enabled=false
    banking.features.blockchain.enabled=false
    banking.features.biometric.enabled=false
    
    # API Documentation
    springdoc.api-docs.path=/api-docs
    springdoc.swagger-ui.path=/swagger-ui.html
    springdoc.swagger-ui.enabled=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: banking-system
  labels:
    app: postgres
data:
  POSTGRES_DB: banking_system
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: banking-system
  labels:
    app: redis
data:
  redis.conf: |
    # Redis Banking Configuration
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    timeout 300
    tcp-keepalive 60
    save 900 1
    save 300 10
    save 60 10000
    
    # Security
    requirepass banking_redis_password
    
    # Performance
    tcp-backlog 511
    databases 16
    
    # Logging
    loglevel notice