apiVersion: v1
kind: Secret
metadata:
  name: banking-app-secrets
  namespace: banking-system
  labels:
    app: enterprise-loan-system
    version: "1.0.0"
    environment: production
    compliance: banking
    tier: application
  annotations:
    description: "Sensitive configuration for Enterprise Loan Management System"
    compliance.banking/encryption: "required"
    compliance.banking/rotation: "90days"
type: Opaque
stringData:
  # Database Connection Secrets (12-Factor: Backing Services)
  DATABASE_PASSWORD: ""  # To be set via external secrets management (AWS Secrets Manager, HashiCorp Vault, etc.)
  DATABASE_USERNAME: "banking_user"
  
  # Redis Authentication (12-Factor: Backing Services)
  REDIS_PASSWORD: ""     # To be set via external secrets management
  
  # Security and Authentication Secrets
  JWT_SECRET: ""         # To be set via external secrets - must be 256-bit for banking compliance
  OAUTH_CLIENT_SECRET: "" # To be set via external secrets for OAuth2 integration
  
  # Banking Compliance Secrets
  FAPI_CLIENT_SECRET: "" # Financial-grade API client secret for Open Banking compliance
  PCI_ENCRYPTION_KEY: "" # PCI DSS compliant encryption key for sensitive data
  
  # External Service Authentication
  CREDIT_BUREAU_API_KEY: ""     # Credit bureau service API key
  PAYMENT_PROCESSOR_SECRET: ""  # Payment processing service secret
  FRAUD_DETECTION_TOKEN: ""     # Fraud detection service authentication token
  
  # Monitoring and Observability Secrets
  PROMETHEUS_AUTH_TOKEN: ""     # Prometheus scraping authentication
  
  # Encryption Keys for Data at Rest
  DATA_ENCRYPTION_KEY: ""       # AES-256 key for encrypting sensitive banking data
  AUDIT_LOG_SIGNING_KEY: ""     # Key for digitally signing audit logs for compliance
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: banking-system
  labels:
    app: postgres
    version: "1.0.0"
    environment: production
    compliance: banking
    tier: database
  annotations:
    description: "PostgreSQL database secrets for banking system"
    compliance.banking/encryption: "required"
type: Opaque
stringData:
  POSTGRES_PASSWORD: ""    # To be set via external secrets management
  POSTGRES_REPLICATION_PASSWORD: ""  # For database replication if required
  POSTGRES_BACKUP_PASSWORD: ""       # For automated backup authentication
---
apiVersion: v1
kind: Secret
metadata:
  name: cache-secrets
  namespace: banking-system
  labels:
    app: redis
    version: "1.0.0"
    environment: production
    compliance: banking
    tier: cache
  annotations:
    description: "Redis cache authentication secrets"
    compliance.banking/encryption: "required"
type: Opaque
stringData:
  REDIS_PASSWORD: ""       # To be set via external secrets management
  REDIS_AUTH_TOKEN: ""     # Additional authentication token if required
---
apiVersion: v1
kind: Secret
metadata:
  name: external-api-secrets
  namespace: banking-system
  labels:
    app: enterprise-loan-system
    version: "1.0.0"
    environment: production
    compliance: banking
    tier: integration
  annotations:
    description: "External service integration secrets for banking APIs"
    compliance.banking/encryption: "required"
type: Opaque
stringData:
  # Service Discovery and Configuration
  EUREKA_USERNAME: ""      # Service registry authentication
  EUREKA_PASSWORD: ""
  
  # Kafka Event Streaming (if authentication required)
  KAFKA_USERNAME: ""       # Kafka SASL authentication
  KAFKA_PASSWORD: ""
  
  # External Banking APIs
  OPEN_BANKING_CLIENT_ID: ""     # Open Banking API client credentials
  OPEN_BANKING_CLIENT_SECRET: ""
  
  # Third-party Financial Services
  SWIFT_API_KEY: ""              # SWIFT network integration
  ACH_PROCESSOR_SECRET: ""       # ACH payment processing
  
  # Regulatory Reporting APIs
  REGULATORY_REPORTING_TOKEN: "" # For automated compliance reporting