apiVersion: v1
kind: Secret
metadata:
  name: banking-app-secrets
  namespace: banking-system
  labels:
    app: enterprise-loan-system
type: Opaque
stringData:
  DATABASE_PASSWORD: ""  # To be set via external secrets or CI/CD
  REDIS_PASSWORD: ""     # To be set via external secrets or CI/CD
  JWT_SECRET: ""         # To be set via external secrets or CI/CD
  FAPI_CLIENT_SECRET: "" # To be set via external secrets or CI/CD
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: banking-system
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: ""  # To be set via external secrets or CI/CD
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: banking-system
  labels:
    app: redis
type: Opaque
stringData:
  REDIS_PASSWORD: ""     # To be set via external secrets or CI/CD