# Kustomization file for AmanahFi Platform Monitoring Stack
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: amanahfi-platform-monitoring
  annotations:
    description: "Monitoring and observability stack for AmanahFi Islamic Finance and CBDC Platform"
    version: "1.0.0"
    maintainer: "AmanahFi Platform Team <platform@amanahfi.ae>"

# Namespace for monitoring resources
namespace: amanahfi-platform

# Common labels for all monitoring resources
commonLabels:
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/managed-by: kustomize
  ae.amanahfi.monitoring: "enabled"
  ae.amanahfi.environment: "production"

# Common annotations
commonAnnotations:
  monitoring.amanahfi.ae/stack: "prometheus-grafana-alertmanager"
  monitoring.amanahfi.ae/version: "1.0.0"
  monitoring.amanahfi.ae/islamic-finance-metrics: "enabled"
  monitoring.amanahfi.ae/cbdc-metrics: "enabled"
  monitoring.amanahfi.ae/regulatory-compliance: "enabled"

# Resources included in this monitoring stack
resources:
- rbac.yaml
- prometheus/prometheus.yaml
- prometheus/rules.yaml
- grafana/grafana.yaml
- grafana/dashboards.yaml
- alertmanager/alertmanager.yaml

# Images used in the monitoring stack
images:
- name: prom/prometheus
  newTag: "v2.47.0"
- name: grafana/grafana
  newTag: "10.1.0"
- name: prom/alertmanager
  newTag: "v0.26.0"
- name: busybox
  newTag: "1.35"

# Patches for environment-specific customizations
patches:
# Production resource requirements for Prometheus
- target:
    kind: Deployment
    name: prometheus
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "4Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "1000m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "8Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "2000m"

# Production storage for Prometheus
- target:
    kind: PersistentVolumeClaim
    name: prometheus-storage
  patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: "500Gi"

# Production resource requirements for Grafana
- target:
    kind: Deployment
    name: grafana
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "1Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "500m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "2Gi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "1000m"

# Strategic merge patches
patchesStrategicMerge:
- patches/prometheus-production.yaml
- patches/grafana-production.yaml
- patches/alertmanager-production.yaml

# ConfigMap generators for dynamic configuration
configMapGenerator:
- name: monitoring-extra-config
  literals:
  - MONITORING_RETENTION_DAYS=30
  - ALERT_ESCALATION_ENABLED=true
  - ISLAMIC_FINANCE_MONITORING=enabled
  - CBDC_MONITORING=enabled
  - REGULATORY_MONITORING=enabled
  - SHARIA_COMPLIANCE_ALERTS=critical
  behavior: merge

# Generate monitoring-specific secrets (commented out - use external secret management)
# secretGenerator:
# - name: monitoring-secrets
#   literals:
#   - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
#   - PAGERDUTY_API_KEY=${PAGERDUTY_API_KEY}
#   type: Opaque

# Name prefix for generated resources
namePrefix: ""

# Name suffix for generated resources
nameSuffix: ""

# Generate name hash suffix for ConfigMaps and Secrets
generatorOptions:
  disableNameSuffixHash: false
  labels:
    generator: kustomize-monitoring
    ae.amanahfi.config-type: monitoring
  annotations:
    config.kubernetes.io/monitoring-config: "true"

# Replacements for dynamic values
replacements:
- source:
    kind: ConfigMap
    name: monitoring-extra-config
    fieldPath: data.MONITORING_RETENTION_DAYS
  targets:
  - select:
      kind: Deployment
      name: prometheus
    fieldPaths:
    - spec.template.spec.containers.[name=prometheus].args.[=--storage.tsdb.retention.time=30d]

# Transformers for additional customizations
transformers:
- transformers/monitoring-labels.yaml
- transformers/monitoring-security.yaml
- transformers/islamic-finance-metrics.yaml
- transformers/cbdc-metrics.yaml

# Validation rules
validators:
- kind: ValidatingAdmissionPolicy
  path: validators/monitoring-resource-limits.yaml
- kind: ValidatingAdmissionPolicy
  path: validators/monitoring-security-standards.yaml
- kind: ValidatingAdmissionPolicy
  path: validators/compliance-monitoring-requirements.yaml

# Build metadata
buildMetadata:
- buildDate
- commitHash
- gitBranch