apiVersion: v1
kind: Service
metadata:
  name: enterprise-banking-service
  labels:
    app: enterprise-banking
    component: loan-management
    tier: application
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app: enterprise-banking
    component: loan-management
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: management
    port: 8081
    targetPort: management
    protocol: TCP
  sessionAffinity: None
  
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-banking-service-external
  labels:
    app: enterprise-banking
    component: loan-management
    tier: application
    exposure: external
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${AWS_SSL_CERT_ARN}"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app: enterprise-banking
    component: loan-management
  ports:
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16

---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-banking-headless
  labels:
    app: enterprise-banking
    component: loan-management
    tier: application
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: enterprise-banking
    component: loan-management
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP